(() => {
const K={"com.packrat.audio-manager-pro.apply-profile":"apply","com.packrat.audio-manager-pro.set-output":"set-output","com.packrat.audio-manager-pro.set-input":"set-input","com.packrat.audio-manager-pro.cycle-profile":"cycle","com.packrat.audio-manager-pro.profile-status":"status","com.packrat.audio-manager-pro.mute-default-mic":"mute-mic","com.packrat.audio-manager-pro.profile-output-volume":"volume"};
const S=[["outputDefault","outputs"],["outputCommunications","outputs"],["inputDefault","inputs"],["inputCommunications","inputs"]];
let ws=null,uuid="",ctx="",aid="",kind="apply",settings={profileId:"",role:"default",device:null,step:2},snap=null,g={profiles:[],lastAppliedProfileId:""},edit="";
const $=id=>document.getElementById(id), norm=v=>String(v||"").normalize("NFKC").trim().replace(/\s+/g," ").toLowerCase();
function send(x){if(ws?.readyState!==WebSocket.OPEN)return false;ws.send(JSON.stringify(x));return true}
function cmd(command,extra={}){return send({event:"sendToPlugin",action:aid,context:ctx,payload:{type:"audioManager.command",command,...extra}})}
function ident(e){return{endpointId:String(e?.id||e?.endpointId||""),name:String(e?.name||""),instanceId:String(e?.instanceId||""),containerId:String(e?.containerId||"").toLowerCase()}}
function resolve(saved,list=[]){if(!saved)return null;let x=list.find(e=>String(e.id)===String(saved.endpointId||""));if(x)return x;if(saved.containerId&&saved.name){const m=list.filter(e=>norm(e.containerId)===norm(saved.containerId)&&norm(e.name)===norm(saved.name));if(m.length===1)return m[0]}return null}
function opt(sel,v,t,s=false){const o=document.createElement("option");o.value=v;o.textContent=t;o.selected=s;sel.appendChild(o)}
function devices(sel,list,saved,blank=true){const found=resolve(saved,list);sel.replaceChildren();if(blank)opt(sel,"","Preserve current / not configured",!saved);else opt(sel,"","Choose a device",!saved);if(saved&&!found)opt(sel,"__saved__",`Missing · ${saved.name||"saved device"} · rebind required`,true);for(const e of list)opt(sel,String(e.id),String(e.name||"Unnamed audio device"),found?.id===e.id)}
function profiles(){return Array.isArray(g.profiles)?g.profiles:[]}function prof(id){return profiles().find(p=>p.id===id)||null}
function saveAction(){const n={...settings};if(["apply","status","volume"].includes(kind))n.profileId=$("actionProfile").value;if(["set-output","set-input"].includes(kind)){n.role=$("actionRole").value==="communications"?"communications":"default";const list=kind==="set-output"?snap?.outputs||[]:snap?.inputs||[],v=$("actionDevice").value;if(!v)n.device=null;else if(v!=="__saved__"){const e=list.find(x=>String(x.id)===v);if(e)n.device=ident(e)}}if(kind==="volume")n.step=Number($("dialStep").value||2);settings=n;send({event:"setSettings",action:aid,context:ctx,payload:n})}
function actionUI(){$("profileAction").hidden=!["apply","status","volume"].includes(kind);$("deviceAction").hidden=!["set-output","set-input"].includes(kind);$("dialAction").hidden=kind!=="volume";if(["apply","status","volume"].includes(kind)){const sel=$("actionProfile"),cur=settings.profileId||"";sel.replaceChildren();opt(sel,"",profiles().length?"Choose a profile":"Create a profile below",!cur);for(const p of profiles())opt(sel,p.id,p.name,p.id===cur);const hint=$("actionProfileHint");const valid=Boolean(cur&&prof(cur));hint.classList.toggle("warn",!valid);hint.textContent=valid?"This action is pinned to the selected Audio Profile.":profiles().length?"Choose a profile before using this action.":"Create an Audio Profile below, then select it here."}if(["set-output","set-input"].includes(kind)){const list=kind==="set-output"?snap?.outputs||[]:snap?.inputs||[];$("actionRole").value=settings.role==="communications"?"communications":"default";devices($("actionDevice"),list,settings.device,false);const hint=$("actionDeviceHint"),resolved=settings.device&&resolve(settings.device,list);hint.classList.toggle("warn",!resolved);hint.textContent=settings.device&&!resolved?"Saved device identity changed. Select the intended device to rebind it.":resolved?"Endpoint identity plus hardware-container metadata are saved when available.":"Choose a device before using this action."}$("dialStep").value=String(settings.step||2)}
function status(r,err){const d=$("statusDot");d.className="dot";if(err||snap?.error){d.classList.add("error");$("statusTitle").textContent="Windows audio unavailable";$("statusDetail").textContent=err||snap?.error}else if(snap){d.classList.add("ready");$("statusTitle").textContent="Windows audio connected";$("statusDetail").textContent=`${snap.outputs?.length||0} outputs · ${snap.inputs?.length||0} inputs · role-aware`}else{d.classList.add("warn");$("statusTitle").textContent="Connecting to Windows audio…"}const b=$("resultBox");if(!r?.status){b.hidden=true;return}const st=String(r.status).toUpperCase(),f=Array.isArray(r.failures)?r.failures:[];b.hidden=false;b.className=`result ${st.toLowerCase()}`;b.textContent=f.length?`${st} · ${f.map(x=>x.error).filter(Boolean).slice(0,2).join(" · ")}`:st}
function editorProfile(){return prof(edit)||profiles()[0]||null}
function stateCtr(k,slot){$(k+"RestoreVolume").checked=slot?.restoreVolume===true;$(k+"Volume").value=Number.isFinite(Number(slot?.volume))?Math.round(Number(slot.volume)):50;$(k+"RestoreMute").checked=slot?.restoreMute===true;$(k+"Muted").value=slot?.muted===true?"true":"false"}
function editor(){const ps=profiles();if(!ps.some(p=>p.id===edit))edit=ps[0]?.id||"";const es=$("editorProfile");es.replaceChildren();opt(es,"",ps.length?"Choose a profile":"No profiles yet",!edit);for(const p of ps)opt(es,p.id,p.name,p.id===edit);const p=editorProfile();$("profileName").value=p?.name||"";$("profileAccent").value=/^#[0-9a-f]{6}$/i.test(String(p?.accent||""))?p.accent:"#56f2a5";$("saveProfile").disabled=!p;$("deleteProfile").disabled=!p;for(const [k,listKey] of S){const slot=p?.slots?.[k]||null;devices($(k+"Device"),Array.isArray(snap?.[listKey])?snap[listKey]:[],slot?.device||null,true);stateCtr(k,slot)}validateEditor()}
function slot(k,listKey,p){const sel=$(k+"Device"),v=sel.value;if(!v)return null;const old=p?.slots?.[k]||null,list=Array.isArray(snap?.[listKey])?snap[listKey]:[];let device=old?.device||null;if(v!=="__saved__"){const e=list.find(x=>String(x.id)===v);device=e?ident(e):null}if(!device)return null;return{device,restoreVolume:$(k+"RestoreVolume").checked,volume:Math.max(0,Math.min(100,Number($(k+"Volume").value||0))),restoreMute:$(k+"RestoreMute").checked,muted:$(k+"Muted").value==="true"}}
function validateEditor(){const box=$("profileValidation"),p=editorProfile();if(!p){box.hidden=true;return}const warnings=[],states=[];for(const [k,l] of S){const sel=$(k+"Device");if(sel.value==="__saved__")warnings.push("A saved device is missing and needs an explicit rebind.");const st=slot(k,l,p);if(st)states.push(st)}if(!states.length)warnings.push("This profile has no configured audio roles.");const seen=new Map();for(const st of states){const d=st.device||{},key=d.endpointId||(d.containerId&&d.name?`${norm(d.containerId)}|${norm(d.name)}`:"");if(!key)continue;const prior=seen.get(key);if(prior){if(st.restoreVolume&&prior.restoreVolume&&Number(st.volume)!==Number(prior.volume))warnings.push("The same device has conflicting saved volumes across roles; volume restore will be skipped.");if(st.restoreMute&&prior.restoreMute&&Boolean(st.muted)!==Boolean(prior.muted))warnings.push("The same device has conflicting saved mute states across roles; mute restore will be skipped.")}else seen.set(key,st)}const unique=[...new Set(warnings)];box.hidden=!unique.length;box.classList.toggle("warn",unique.length>0);box.textContent=unique.join(" ")}
function saveProfile(){const p=editorProfile();if(!p)return;const n={schemaVersion:1,id:p.id,name:$("profileName").value.trim().slice(0,80)||p.name,accent:$("profileAccent").value.toUpperCase(),slots:{}};for(const [k,l] of S)n.slots[k]=slot(k,l,p);cmd("save-profile",{profile:n})}
function render(st={}){snap=st.snapshot||snap;g=st.globalSettings||g;status(st.lastResult,st.latestError);actionUI();editor()}
window.connectElgatoStreamDeckSocket=(port,u,reg,info,raw)=>{uuid=u;const a=JSON.parse(raw||"{}");ctx=String(a.context||u);aid=String(a.action||"");kind=K[aid]||"apply";settings={...settings,...(a.payload?.settings||{})};actionUI();ws=new WebSocket(`ws://127.0.0.1:${port}`);ws.onopen=()=>{send({event:reg,uuid});send({event:"getSettings",action:aid,context:ctx});send({event:"sendToPlugin",action:aid,context:ctx,payload:{type:"audioManager.inspect"}})};ws.onmessage=e=>{let m;try{m=JSON.parse(e.data)}catch{return}if(m.event==="didReceiveSettings"){settings={...settings,...(m.payload?.settings||{})};actionUI()}if(m.event==="sendToPropertyInspector"&&m.payload?.type==="audioManager.state")render(m.payload)}};
$("actionProfile").addEventListener("change",saveAction);$("actionRole").addEventListener("change",saveAction);$("actionDevice").addEventListener("change",saveAction);$("dialStep").addEventListener("change",saveAction);$("refresh").addEventListener("click",()=>cmd("refresh"));$("captureCurrent").addEventListener("click",()=>cmd("create-profile",{name:$("profileName").value.trim()||`Audio Profile ${profiles().length+1}`}));$("editorProfile").addEventListener("change",()=>{edit=$("editorProfile").value;editor()});for(const [k] of S){for(const suffix of ["Device","RestoreVolume","Volume","RestoreMute","Muted"]){$(k+suffix).addEventListener("change",validateEditor)}}$("saveProfile").addEventListener("click",saveProfile);$("deleteProfile").addEventListener("click",()=>{const p=editorProfile();if(p){cmd("delete-profile",{profileId:p.id});edit=""}});
})();
