/**
 * MENS-COLLEGE-BASKETBALL teams, generated from ESPN by plugins/_shared/scripts/gen_teams.py.
 * Do not hand edit: rerun the script to refresh.
 *
 * Colours are the official team colours, used as the key's colour spine. They are the only
 * team branding this product ever renders. No logos, crests or wordmarks, anywhere.
 */
import type { SportTeam } from "../../../_shared/src/sport";

export const CBB_TEAMS: SportTeam[] = [
	{ id: "2046", abbr: "APSU", name: "Austin Peay Governors", color: "#8e0b0b", altColor: "#f5faf8", conference: "ASUN", division: "Atlantic Sun Conference" },
	{ id: "91", abbr: "BELL", name: "Bellarmine Knights", color: "#000000", altColor: "#f5faf8", conference: "ASUN", division: "Atlantic Sun Conference" },
	{ id: "2110", abbr: "CARK", name: "Central Arkansas Bears", color: "#a7a9ac", altColor: "#8e959a", conference: "ASUN", division: "Atlantic Sun Conference" },
	{ id: "2198", abbr: "EKU", name: "Eastern Kentucky Colonels", color: "#660819", altColor: "#f0f0f0", conference: "ASUN", division: "Atlantic Sun Conference" },
	{ id: "526", abbr: "FGCU", name: "Florida Gulf Coast Eagles", color: "#00885a", altColor: "#076c3b", conference: "ASUN", division: "Atlantic Sun Conference" },
	{ id: "294", abbr: "JAX", name: "Jacksonville Dolphins", color: "#00523e", altColor: "#f5faf8", conference: "ASUN", division: "Atlantic Sun Conference" },
	{ id: "288", abbr: "LIP", name: "Lipscomb Bisons", color: "#20366c", altColor: "#f6b734", conference: "ASUN", division: "Atlantic Sun Conference" },
	{ id: "2453", abbr: "UNA", name: "North Alabama Lions", color: "#663399", altColor: "#f5faf8", conference: "ASUN", division: "Atlantic Sun Conference" },
	{ id: "2454", abbr: "UNF", name: "North Florida Ospreys", color: "#004b8d", altColor: "#babcbe", conference: "ASUN", division: "Atlantic Sun Conference" },
	{ id: "56", abbr: "STET", name: "Stetson Hatters", color: "#0a5640", altColor: "#56854e", conference: "ASUN", division: "Atlantic Sun Conference" },
	{ id: "2698", abbr: "WGA", name: "West Georgia Wolves", color: "#0033a1", altColor: "#db1a21", conference: "ASUN", division: "Atlantic Sun Conference" },
	{ id: "2429", abbr: "CLT", name: "Charlotte 49ers", color: "#005035", altColor: "#a49665", conference: "American", division: "American Conference" },
	{ id: "151", abbr: "ECU", name: "East Carolina Pirates", color: "#582c83", altColor: "#ffc72c", conference: "American", division: "American Conference" },
	{ id: "2226", abbr: "FAU", name: "Florida Atlantic Owls", color: "#003366", altColor: "#cc0000", conference: "American", division: "American Conference" },
	{ id: "235", abbr: "MEM", name: "Memphis Tigers", color: "#004991", altColor: "#8e908f", conference: "American", division: "American Conference" },
	{ id: "249", abbr: "UNT", name: "North Texas Mean Green", color: "#068f33", altColor: "#ffffff", conference: "American", division: "American Conference" },
	{ id: "242", abbr: "RICE", name: "Rice Owls", color: "#00205b", altColor: "#c1c6c8", conference: "American", division: "American Conference" },
	{ id: "58", abbr: "USF", name: "South Florida Bulls", color: "#006747", altColor: "#cfc493", conference: "American", division: "American Conference" },
	{ id: "218", abbr: "TEM", name: "Temple Owls", color: "#a41e35", altColor: "#ffffff", conference: "American", division: "American Conference" },
	{ id: "2655", abbr: "TULN", name: "Tulane Green Wave", color: "#006747", altColor: "#418fde", conference: "American", division: "American Conference" },
	{ id: "202", abbr: "TLSA", name: "Tulsa Golden Hurricane", color: "#003595", altColor: "#d0b787", conference: "American", division: "American Conference" },
	{ id: "5", abbr: "UAB", name: "UAB Blazers", color: "#1a5632", altColor: "#fdb913", conference: "American", division: "American Conference" },
	{ id: "2636", abbr: "UTSA", name: "UTSA Roadrunners", color: "#0c2340", altColor: "#f15a22", conference: "American", division: "American Conference" },
	{ id: "2724", abbr: "WICH", name: "Wichita State Shockers", color: "#ffcd00", altColor: "#27251f", conference: "American", division: "American Conference" },
	{ id: "2099", abbr: "CAN", name: "Canisius Golden Griffins", color: "#004a81", altColor: "#dda50f", conference: "Metro", division: "Metro Conference" },
	{ id: "2217", abbr: "FAIR", name: "Fairfield Stags", color: "#000000", altColor: "#ebebeb", conference: "Metro", division: "Metro Conference" },
	{ id: "314", abbr: "IONA", name: "Iona Gaels", color: "#6f2c3e", altColor: "#f0ab00", conference: "Metro", division: "Metro Conference" },
	{ id: "2363", abbr: "MAN", name: "Manhattan Jaspers", color: "#4f8537", altColor: "#b5b7ba", conference: "Metro", division: "Metro Conference" },
	{ id: "2368", abbr: "MRST", name: "Marist Red Foxes", color: "#e53730", altColor: "#f0f0f0", conference: "Metro", division: "Metro Conference" },
	{ id: "2771", abbr: "MRMK", name: "Merrimack Warriors", color: "#2f4f93", altColor: "#e8c535", conference: "Metro", division: "Metro Conference" },
	{ id: "116", abbr: "MSM", name: "Mount St. Mary's Mountaineers", color: "#005596", altColor: "#ebebeb", conference: "Metro", division: "Metro Conference" },
	{ id: "315", abbr: "NIA", name: "Niagara Purple Eagles", color: "#69207e", altColor: "#f0f0f0", conference: "Metro", division: "Metro Conference" },
	{ id: "2514", abbr: "QUIN", name: "Quinnipiac Bobcats", color: "#041b43", altColor: "#f5faf8", conference: "Metro", division: "Metro Conference" },
	{ id: "2520", abbr: "RID", name: "Rider Broncs", color: "#a80532", altColor: "#ebebeb", conference: "Metro", division: "Metro Conference" },
	{ id: "2529", abbr: "SHU", name: "Sacred Heart Pioneers", color: "#a40012", altColor: "#c29472", conference: "Metro", division: "Metro Conference" },
	{ id: "2612", abbr: "SPU", name: "Saint Peter's Peacocks", color: "#004cc2", altColor: "#f5faf8", conference: "Metro", division: "Metro Conference" },
	{ id: "2561", abbr: "SIE", name: "Siena Saints", color: "#037961", altColor: "#eea60f", conference: "Metro", division: "Metro Conference" },
	{ id: "2000", abbr: "ACU", name: "Abilene Christian Wildcats", color: "#592d82", altColor: "#b1b3b3", conference: "UAC", division: "United Athletic Conference" },
	{ id: "2856", abbr: "CBU", name: "California Baptist Lancers", color: "#000080", altColor: "#f5faf8", conference: "UAC", division: "United Athletic Conference" },
	{ id: "253", abbr: "SUU", name: "Southern Utah Thunderbirds", color: "#c72026", altColor: "#000000", conference: "UAC", division: "United Athletic Conference" },
	{ id: "2627", abbr: "TAR", name: "Tarleton State Texans", color: "#000000", altColor: "#f5faf8", conference: "UAC", division: "United Athletic Conference" },
	{ id: "250", abbr: "UTA", name: "UT Arlington Mavericks", color: "#004b7c", altColor: "#f58024", conference: "UAC", division: "United Athletic Conference" },
	{ id: "3101", abbr: "UTU", name: "Utah Tech Trailblazers", color: "#000000", altColor: "#f5faf8", conference: "UAC", division: "United Athletic Conference" },
	{ id: "3084", abbr: "UVU", name: "Utah Valley Wolverines", color: "#004812", altColor: "#e1c736", conference: "UAC", division: "United Athletic Conference" },
	{ id: "103", abbr: "BC", name: "Boston College Eagles", color: "#8c2232", altColor: "#dbcca6", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "25", abbr: "CAL", name: "California Golden Bears", color: "#041e42", altColor: "#ffc72c", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "228", abbr: "CLEM", name: "Clemson Tigers", color: "#f56600", altColor: "#ffffff", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "150", abbr: "DUKE", name: "Duke Blue Devils", color: "#00539b", altColor: "#ffffff", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "52", abbr: "FSU", name: "Florida State Seminoles", color: "#782f40", altColor: "#ceb888", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "59", abbr: "GT", name: "Georgia Tech Yellow Jackets", color: "#b3a369", altColor: "#ffffff", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "97", abbr: "LOU", name: "Louisville Cardinals", color: "#c9001f", altColor: "#ffffff", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "2390", abbr: "MIA", name: "Miami Hurricanes", color: "#f47423", altColor: "#035131", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "152", abbr: "NCSU", name: "NC State Wolfpack", color: "#cc0000", altColor: "#ffffff", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "153", abbr: "UNC", name: "North Carolina Tar Heels", color: "#7bafd4", altColor: "#13294b", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "87", abbr: "ND", name: "Notre Dame Fighting Irish", color: "#062340", altColor: "#c99700", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "221", abbr: "PITT", name: "Pittsburgh Panthers", color: "#003594", altColor: "#ffb81c", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "2567", abbr: "SMU", name: "SMU Mustangs", color: "#a80000", altColor: "#0033a1", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "24", abbr: "STAN", name: "Stanford Cardinal", color: "#8c1515", altColor: "#ffffff", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "183", abbr: "SYR", name: "Syracuse Orange", color: "#000e54", altColor: "#ff431b", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "258", abbr: "UVA", name: "Virginia Cavaliers", color: "#232d4b", altColor: "#f84c1e", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "259", abbr: "VT", name: "Virginia Tech Hokies", color: "#6a2c3e", altColor: "#cf4520", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "154", abbr: "WAKE", name: "Wake Forest Demon Deacons", color: "#ceb888", altColor: "#2c2a29", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "2066", abbr: "BING", name: "Binghamton Bearcats", color: "#00614a", altColor: "#f0f0f0", conference: "aeast", division: "America East Conference" },
	{ id: "2803", abbr: "BRY", name: "Bryant Bulldogs", color: "#000000", altColor: "#9f8343", conference: "aeast", division: "America East Conference" },
	{ id: "311", abbr: "ME", name: "Maine Black Bears", color: "#127dbe", altColor: "#f5faf8", conference: "aeast", division: "America East Conference" },
	{ id: "2885", abbr: "NJIT", name: "NJIT Highlanders", color: "#ee3024", altColor: "#df3e2e", conference: "aeast", division: "America East Conference" },
	{ id: "160", abbr: "UNH", name: "New Hampshire Wildcats", color: "#004990", altColor: "#c3c4c6", conference: "aeast", division: "America East Conference" },
	{ id: "399", abbr: "UALB", name: "UAlbany Great Danes", color: "#3d2777", altColor: "#ffffff", conference: "aeast", division: "America East Conference" },
	{ id: "2378", abbr: "UMBC", name: "UMBC Retrievers", color: "#000000", altColor: "#ad860a", conference: "aeast", division: "America East Conference" },
	{ id: "2349", abbr: "UML", name: "UMass Lowell River Hawks", color: "#00529c", altColor: "#cf1f2f", conference: "aeast", division: "America East Conference" },
	{ id: "261", abbr: "UVM", name: "Vermont Catamounts", color: "#154734", altColor: "#ffc72c", conference: "aeast", division: "America East Conference" },
	{ id: "2166", abbr: "DAV", name: "Davidson Wildcats", color: "#000000", altColor: "#e51837", conference: "atl10", division: "Atlantic 10 Conference" },
	{ id: "2168", abbr: "DAY", name: "Dayton Flyers", color: "#004b8d", altColor: "#ffffff", conference: "atl10", division: "Atlantic 10 Conference" },
	{ id: "2184", abbr: "DUQ", name: "Duquesne Dukes", color: "#002d62", altColor: "#b90b2e", conference: "atl10", division: "Atlantic 10 Conference" },
	{ id: "2230", abbr: "FOR", name: "Fordham Rams", color: "#830032", altColor: "#909090", conference: "atl10", division: "Atlantic 10 Conference" },
	{ id: "2244", abbr: "GMU", name: "George Mason Patriots", color: "#016600", altColor: "#ecb010", conference: "atl10", division: "Atlantic 10 Conference" },
	{ id: "45", abbr: "GW", name: "George Washington Revolutionaries", color: "#002843", altColor: "#e8d2a1", conference: "atl10", division: "Atlantic 10 Conference" },
	{ id: "2325", abbr: "LAS", name: "La Salle Explorers", color: "#003356", altColor: "#ffce00", conference: "atl10", division: "Atlantic 10 Conference" },
	{ id: "2350", abbr: "LUC", name: "Loyola Chicago Ramblers", color: "#9d1244", altColor: "#f5faf8", conference: "atl10", division: "Atlantic 10 Conference" },
	{ id: "227", abbr: "URI", name: "Rhode Island Rams", color: "#091f3f", altColor: "#5ab3e8", conference: "atl10", division: "Atlantic 10 Conference" },
	{ id: "257", abbr: "RICH", name: "Richmond Spiders", color: "#9e0712", altColor: "#b90b2e", conference: "atl10", division: "Atlantic 10 Conference" },
	{ id: "2603", abbr: "JOES", name: "Saint Joseph's Hawks", color: "#9e1b32", altColor: "#6c6f70", conference: "atl10", division: "Atlantic 10 Conference" },
	{ id: "139", abbr: "SLU", name: "Saint Louis Billikens", color: "#00539c", altColor: "#ebebeb", conference: "atl10", division: "Atlantic 10 Conference" },
	{ id: "179", abbr: "SBU", name: "St. Bonaventure Bonnies", color: "#70261d", altColor: "#f5faf8", conference: "atl10", division: "Atlantic 10 Conference" },
	{ id: "2670", abbr: "VCU", name: "VCU Rams", color: "#ffaf00", altColor: "#000000", conference: "atl10", division: "Atlantic 10 Conference" },
	{ id: "2026", abbr: "APP", name: "App State Mountaineers", color: "#000000", altColor: "#ffcd00", conference: "belt", division: "Sun Belt Conference" },
	{ id: "2032", abbr: "ARST", name: "Arkansas State Red Wolves", color: "#cc092f", altColor: "#000000", conference: "belt", division: "Sun Belt Conference" },
	{ id: "324", abbr: "CCU", name: "Coastal Carolina Chanticleers", color: "#006f71", altColor: "#a27752", conference: "belt", division: "Sun Belt Conference" },
	{ id: "290", abbr: "GASO", name: "Georgia Southern Eagles", color: "#041e42", altColor: "#a3aaae", conference: "belt", division: "Sun Belt Conference" },
	{ id: "2247", abbr: "GAST", name: "Georgia State Panthers", color: "#0039a6", altColor: "#ffffff", conference: "belt", division: "Sun Belt Conference" },
	{ id: "256", abbr: "JMU", name: "James Madison Dukes", color: "#450084", altColor: "#cbb677", conference: "belt", division: "Sun Belt Conference" },
	{ id: "309", abbr: "UL", name: "Louisiana Ragin' Cajuns", color: "#ce181e", altColor: "#000000", conference: "belt", division: "Sun Belt Conference" },
	{ id: "276", abbr: "MRSH", name: "Marshall Thundering Herd", color: "#00b140", altColor: "#000000", conference: "belt", division: "Sun Belt Conference" },
	{ id: "295", abbr: "ODU", name: "Old Dominion Monarchs", color: "#003768", altColor: "#a1d2f1", conference: "belt", division: "Sun Belt Conference" },
	{ id: "6", abbr: "USA", name: "South Alabama Jaguars", color: "#00205b", altColor: "#bf0d3e", conference: "belt", division: "Sun Belt Conference" },
	{ id: "2572", abbr: "USM", name: "Southern Miss Golden Eagles", color: "#ffc72c", altColor: "#231f20", conference: "belt", division: "Sun Belt Conference" },
	{ id: "326", abbr: "TXST", name: "Texas State Bobcats", color: "#501214", altColor: "#6a5638", conference: "belt", division: "Sun Belt Conference" },
	{ id: "2653", abbr: "TROY", name: "Troy Trojans", color: "#862633", altColor: "#b1b1b1", conference: "belt", division: "Sun Belt Conference" },
	{ id: "2433", abbr: "ULM", name: "UL Monroe Warhawks", color: "#840029", altColor: "#fdb913", conference: "belt", division: "Sun Belt Conference" },
	{ id: "356", abbr: "ILL", name: "Illinois Fighting Illini", color: "#ff5f05", altColor: "#13294b", conference: "big10", division: "Big Ten Conference" },
	{ id: "84", abbr: "IU", name: "Indiana Hoosiers", color: "#970310", altColor: "#ffffff", conference: "big10", division: "Big Ten Conference" },
	{ id: "2294", abbr: "IOWA", name: "Iowa Hawkeyes", color: "#231f20", altColor: "#fcd116", conference: "big10", division: "Big Ten Conference" },
	{ id: "120", abbr: "MD", name: "Maryland Terrapins", color: "#ce1126", altColor: "#ffffff", conference: "big10", division: "Big Ten Conference" },
	{ id: "127", abbr: "MSU", name: "Michigan State Spartans", color: "#173f35", altColor: "#ffffff", conference: "big10", division: "Big Ten Conference" },
	{ id: "130", abbr: "MICH", name: "Michigan Wolverines", color: "#00274c", altColor: "#ffcb05", conference: "big10", division: "Big Ten Conference" },
	{ id: "135", abbr: "MINN", name: "Minnesota Golden Gophers", color: "#5e0a2f", altColor: "#fab41c", conference: "big10", division: "Big Ten Conference" },
	{ id: "158", abbr: "NEB", name: "Nebraska Cornhuskers", color: "#e31937", altColor: "#ffffff", conference: "big10", division: "Big Ten Conference" },
	{ id: "77", abbr: "NU", name: "Northwestern Wildcats", color: "#492f92", altColor: "#ffffff", conference: "big10", division: "Big Ten Conference" },
	{ id: "194", abbr: "OSU", name: "Ohio State Buckeyes", color: "#ba0c2f", altColor: "#a8adb4", conference: "big10", division: "Big Ten Conference" },
	{ id: "2483", abbr: "ORE", name: "Oregon Ducks", color: "#00934b", altColor: "#fff41b", conference: "big10", division: "Big Ten Conference" },
	{ id: "213", abbr: "PSU", name: "Penn State Nittany Lions", color: "#061440", altColor: "#ffffff", conference: "big10", division: "Big Ten Conference" },
	{ id: "2509", abbr: "PUR", name: "Purdue Boilermakers", color: "#ceb888", altColor: "#000000", conference: "big10", division: "Big Ten Conference" },
	{ id: "164", abbr: "RUTG", name: "Rutgers Scarlet Knights", color: "#ce0e2d", altColor: "#ffffff", conference: "big10", division: "Big Ten Conference" },
	{ id: "26", abbr: "UCLA", name: "UCLA Bruins", color: "#2774ae", altColor: "#f2a900", conference: "big10", division: "Big Ten Conference" },
	{ id: "30", abbr: "USC", name: "USC Trojans", color: "#9d2235", altColor: "#ffc72c", conference: "big10", division: "Big Ten Conference" },
	{ id: "264", abbr: "WASH", name: "Washington Huskies", color: "#33006f", altColor: "#e8d3a2", conference: "big10", division: "Big Ten Conference" },
	{ id: "275", abbr: "WIS", name: "Wisconsin Badgers", color: "#a00000", altColor: "#ffffff", conference: "big10", division: "Big Ten Conference" },
	{ id: "9", abbr: "ASU", name: "Arizona State Sun Devils", color: "#ffc627", altColor: "#8c1d40", conference: "big12", division: "Big 12 Conference" },
	{ id: "12", abbr: "ARIZ", name: "Arizona Wildcats", color: "#cc0033", altColor: "#003366", conference: "big12", division: "Big 12 Conference" },
	{ id: "252", abbr: "BYU", name: "BYU Cougars", color: "#0047ba", altColor: "#002e5d", conference: "big12", division: "Big 12 Conference" },
	{ id: "239", abbr: "BAY", name: "Baylor Bears", color: "#154734", altColor: "#ffb81c", conference: "big12", division: "Big 12 Conference" },
	{ id: "2132", abbr: "CIN", name: "Cincinnati Bearcats", color: "#000000", altColor: "#e00122", conference: "big12", division: "Big 12 Conference" },
	{ id: "38", abbr: "COLO", name: "Colorado Buffaloes", color: "#cfb87c", altColor: "#000000", conference: "big12", division: "Big 12 Conference" },
	{ id: "248", abbr: "HOU", name: "Houston Cougars", color: "#c8102e", altColor: "#ffffff", conference: "big12", division: "Big 12 Conference" },
	{ id: "66", abbr: "ISU", name: "Iowa State Cyclones", color: "#ae192d", altColor: "#ffc72a", conference: "big12", division: "Big 12 Conference" },
	{ id: "2305", abbr: "KU", name: "Kansas Jayhawks", color: "#0051ba", altColor: "#e8000d", conference: "big12", division: "Big 12 Conference" },
	{ id: "2306", abbr: "KSU", name: "Kansas State Wildcats", color: "#330a57", altColor: "#e2e3e4", conference: "big12", division: "Big 12 Conference" },
	{ id: "197", abbr: "OKST", name: "Oklahoma State Cowboys", color: "#fe5c00", altColor: "#000000", conference: "big12", division: "Big 12 Conference" },
	{ id: "2628", abbr: "TCU", name: "TCU Horned Frogs", color: "#4d1979", altColor: "#ffffff", conference: "big12", division: "Big 12 Conference" },
	{ id: "2641", abbr: "TTU", name: "Texas Tech Red Raiders", color: "#da291c", altColor: "#000000", conference: "big12", division: "Big 12 Conference" },
	{ id: "2116", abbr: "UCF", name: "UCF Knights", color: "#000000", altColor: "#b4a169", conference: "big12", division: "Big 12 Conference" },
	{ id: "254", abbr: "UTAH", name: "Utah Utes", color: "#be0000", altColor: "#ffffff", conference: "big12", division: "Big 12 Conference" },
	{ id: "277", abbr: "WVU", name: "West Virginia Mountaineers", color: "#eaaa00", altColor: "#002855", conference: "big12", division: "Big 12 Conference" },
	{ id: "2086", abbr: "BTLR", name: "Butler Bulldogs", color: "#0d1361", altColor: "#00a3e0", conference: "bige", division: "Big East Conference" },
	{ id: "156", abbr: "CREI", name: "Creighton Bluejays", color: "#005ca9", altColor: "#6cadde", conference: "bige", division: "Big East Conference" },
	{ id: "305", abbr: "DEP", name: "DePaul Blue Demons", color: "#2d649c", altColor: "#ce1125", conference: "bige", division: "Big East Conference" },
	{ id: "46", abbr: "GTWN", name: "Georgetown Hoyas", color: "#110e42", altColor: "#001c58", conference: "bige", division: "Big East Conference" },
	{ id: "269", abbr: "MARQ", name: "Marquette Golden Eagles", color: "#003366", altColor: "#ffcc00", conference: "bige", division: "Big East Conference" },
	{ id: "2507", abbr: "PROV", name: "Providence Friars", color: "#000000", altColor: "#a3a19e", conference: "bige", division: "Big East Conference" },
	{ id: "2550", abbr: "HALL", name: "Seton Hall Pirates", color: "#0857b1", altColor: "#8a8d8f", conference: "bige", division: "Big East Conference" },
	{ id: "2599", abbr: "SJU", name: "St. John's Red Storm", color: "#d10000", altColor: "#101010", conference: "bige", division: "Big East Conference" },
	{ id: "41", abbr: "CONN", name: "UConn Huskies", color: "#0c2340", altColor: "#a2aaad", conference: "bige", division: "Big East Conference" },
	{ id: "222", abbr: "VILL", name: "Villanova Wildcats", color: "#00205b", altColor: "#13b5ea", conference: "bige", division: "Big East Conference" },
	{ id: "2752", abbr: "XAV", name: "Xavier Musketeers", color: "#21304e", altColor: "#a5a7a8", conference: "bige", division: "Big East Conference" },
	{ id: "13", abbr: "CP", name: "Cal Poly Mustangs", color: "#1e4d2b", altColor: "#eed897", conference: "bigw", division: "Big West Conference" },
	{ id: "2934", abbr: "CSUB", name: "Cal State Bakersfield Roadrunners", color: "#003bab", altColor: "#f5faf8", conference: "bigw", division: "Big West Conference" },
	{ id: "2239", abbr: "CSUF", name: "Cal State Fullerton Titans", color: "#003767", altColor: "#ff8300", conference: "bigw", division: "Big West Conference" },
	{ id: "2463", abbr: "CSUN", name: "Cal State Northridge Matadors", color: "#b50000", altColor: "#f5faf8", conference: "bigw", division: "Big West Conference" },
	{ id: "62", abbr: "HAW", name: "Hawai'i Rainbow Warriors", color: "#005737", altColor: "#000000", conference: "bigw", division: "Big West Conference" },
	{ id: "299", abbr: "LBSU", name: "Long Beach State Beach", color: "#000000", altColor: "#f1f2f3", conference: "bigw", division: "Big West Conference" },
	{ id: "302", abbr: "UCD", name: "UC Davis Aggies", color: "#002855", altColor: "#c3c4c6", conference: "bigw", division: "Big West Conference" },
	{ id: "300", abbr: "UCI", name: "UC Irvine Anteaters", color: "#002b5c", altColor: "#fec52e", conference: "bigw", division: "Big West Conference" },
	{ id: "27", abbr: "UCR", name: "UC Riverside Highlanders", color: "#14234f", altColor: "#f5faf8", conference: "bigw", division: "Big West Conference" },
	{ id: "28", abbr: "UCSD", name: "UC San Diego Tritons", color: "#000000", altColor: "#ffcd00", conference: "bigw", division: "Big West Conference" },
	{ id: "2540", abbr: "UCSB", name: "UC Santa Barbara Gauchos", color: "#1e1840", altColor: "#febc11", conference: "bigw", division: "Big West Conference" },
	{ id: "331", abbr: "EWU", name: "Eastern Washington Eagles", color: "#a10022", altColor: "#abb4bc", conference: "bsky", division: "Big Sky Conference" },
	{ id: "304", abbr: "IDST", name: "Idaho State Bengals", color: "#ef8c00", altColor: "#e9a126", conference: "bsky", division: "Big Sky Conference" },
	{ id: "70", abbr: "IDHO", name: "Idaho Vandals", color: "#000000", altColor: "#8c6e4a", conference: "bsky", division: "Big Sky Conference" },
	{ id: "149", abbr: "MONT", name: "Montana Grizzlies", color: "#751d4a", altColor: "#666666", conference: "bsky", division: "Big Sky Conference" },
	{ id: "147", abbr: "MTST", name: "Montana State Bobcats", color: "#00205c", altColor: "#bc955c", conference: "bsky", division: "Big Sky Conference" },
	{ id: "2464", abbr: "NAU", name: "Northern Arizona Lumberjacks", color: "#003976", altColor: "#1b3069", conference: "bsky", division: "Big Sky Conference" },
	{ id: "2458", abbr: "UNCO", name: "Northern Colorado Bears", color: "#13558d", altColor: "#ffc533", conference: "bsky", division: "Big Sky Conference" },
	{ id: "2502", abbr: "PRST", name: "Portland State Vikings", color: "#00311e", altColor: "#ebebeb", conference: "bsky", division: "Big Sky Conference" },
	{ id: "16", abbr: "SAC", name: "Sacramento State Hornets", color: "#00573c", altColor: "#cdb97d", conference: "bsky", division: "Big Sky Conference" },
	{ id: "2692", abbr: "WEB", name: "Weber State Wildcats", color: "#18005a", altColor: "#ebebeb", conference: "bsky", division: "Big Sky Conference" },
	{ id: "2127", abbr: "CHSO", name: "Charleston Southern Buccaneers", color: "#2e3192", altColor: "#ded090", conference: "bsou", division: "Big South Conference" },
	{ id: "2241", abbr: "GWEB", name: "Gardner-Webb Runnin' Bulldogs", color: "#c12535", altColor: "#909090", conference: "bsou", division: "Big South Conference" },
	{ id: "2272", abbr: "HPU", name: "High Point Panthers", color: "#330072", altColor: "#ffffff", conference: "bsou", division: "Big South Conference" },
	{ id: "2344", abbr: "LONG", name: "Longwood Lancers", color: "#003273", altColor: "#9ea2a3", conference: "bsou", division: "Big South Conference" },
	{ id: "2506", abbr: "PRES", name: "Presbyterian Blue Hose", color: "#194896", altColor: "#990134", conference: "bsou", division: "Big South Conference" },
	{ id: "2515", abbr: "RAD", name: "Radford Highlanders", color: "#bc1515", altColor: "#c2c3c0", conference: "bsou", division: "Big South Conference" },
	{ id: "2908", abbr: "UPST", name: "South Carolina Upstate Spartans", color: "#008545", altColor: "#000000", conference: "bsou", division: "Big South Conference" },
	{ id: "2427", abbr: "UNCA", name: "UNC Asheville Bulldogs", color: "#003da5", altColor: "#ffffff", conference: "bsou", division: "Big South Conference" },
	{ id: "2737", abbr: "WIN", name: "Winthrop Eagles", color: "#9e0b0e", altColor: "#fdb41e", conference: "bsou", division: "Big South Conference" },
	{ id: "2097", abbr: "CAM", name: "Campbell Fighting Camels", color: "#000000", altColor: "#f5faf8", conference: "col", division: "Coastal Athletic Association" },
	{ id: "232", abbr: "COFC", name: "Charleston Cougars", color: "#7a2531", altColor: "#9e8959", conference: "col", division: "Coastal Athletic Association" },
	{ id: "2182", abbr: "DREX", name: "Drexel Dragons", color: "#020260", altColor: "#ffd65a", conference: "col", division: "Coastal Athletic Association" },
	{ id: "2210", abbr: "ELON", name: "Elon Phoenix", color: "#020303", altColor: "#b59a57", conference: "col", division: "Coastal Athletic Association" },
	{ id: "2261", abbr: "HAMP", name: "Hampton Pirates", color: "#0067ac", altColor: "#f5faf8", conference: "col", division: "Coastal Athletic Association" },
	{ id: "2275", abbr: "HOF", name: "Hofstra Pride", color: "#003594", altColor: "#ffc72c", conference: "col", division: "Coastal Athletic Association" },
	{ id: "2405", abbr: "MONM", name: "Monmouth Hawks", color: "#051844", altColor: "#f5faf8", conference: "col", division: "Coastal Athletic Association" },
	{ id: "2448", abbr: "NCAT", name: "North Carolina A&T Aggies", color: "#0505aa", altColor: "#004684", conference: "col", division: "Coastal Athletic Association" },
	{ id: "111", abbr: "NE", name: "Northeastern Huskies", color: "#cc0001", altColor: "#c2c3c0", conference: "col", division: "Coastal Athletic Association" },
	{ id: "2619", abbr: "STBK", name: "Stony Brook Seawolves", color: "#990000", altColor: "#f5faf8", conference: "col", division: "Coastal Athletic Association" },
	{ id: "119", abbr: "TOW", name: "Towson Tigers", color: "#ffc229", altColor: "#f5faf8", conference: "col", division: "Coastal Athletic Association" },
	{ id: "350", abbr: "UNCW", name: "UNC Wilmington Seahawks", color: "#00665e", altColor: "#ffda00", conference: "col", division: "Coastal Athletic Association" },
	{ id: "2729", abbr: "W&M", name: "William & Mary Tribe", color: "#115740", altColor: "#f0b323", conference: "col", division: "Coastal Athletic Association" },
	{ id: "325", abbr: "CLE", name: "Cleveland State Vikings", color: "#006633", altColor: "#231f20", conference: "hor", division: "Horizon League" },
	{ id: "2174", abbr: "DETM", name: "Detroit Mercy Titans", color: "#165b9e", altColor: "#d31733", conference: "hor", division: "Horizon League" },
	{ id: "2739", abbr: "GB", name: "Green Bay Phoenix", color: "#006633", altColor: "#ffffff", conference: "hor", division: "Horizon League" },
	{ id: "85", abbr: "IUIN", name: "IU Indianapolis Jaguars", color: "#a81f30", altColor: "#d59f0f", conference: "hor", division: "Horizon League" },
	{ id: "270", abbr: "MILW", name: "Milwaukee Panthers", color: "#000000", altColor: "#ffc20e", conference: "hor", division: "Horizon League" },
	{ id: "94", abbr: "NKU", name: "Northern Kentucky Norse", color: "#ffc82e", altColor: "#000000", conference: "hor", division: "Horizon League" },
	{ id: "2473", abbr: "OAK", name: "Oakland Golden Grizzlies", color: "#04091c", altColor: "#bc955c", conference: "hor", division: "Horizon League" },
	{ id: "2870", abbr: "PFW", name: "Purdue Fort Wayne Mastodons", color: "#cfb991", altColor: "#000000", conference: "hor", division: "Horizon League" },
	{ id: "2523", abbr: "RMU", name: "Robert Morris Colonials", color: "#00214d", altColor: "#a21d2b", conference: "hor", division: "Horizon League" },
	{ id: "2750", abbr: "WRST", name: "Wright State Raiders", color: "#cba052", altColor: "#cba052", conference: "hor", division: "Horizon League" },
	{ id: "2754", abbr: "YSU", name: "Youngstown State Penguins", color: "#e51935", altColor: "#690717", conference: "hor", division: "Horizon League" },
	{ id: "225", abbr: "BRWN", name: "Brown Bears", color: "#411e09", altColor: "#949300", conference: "ivy", division: "Ivy League" },
	{ id: "171", abbr: "COLU", name: "Columbia Lions", color: "#7ba4db", altColor: "#183863", conference: "ivy", division: "Ivy League" },
	{ id: "172", abbr: "COR", name: "Cornell Big Red", color: "#b31b1b", altColor: "#ffffff", conference: "ivy", division: "Ivy League" },
	{ id: "159", abbr: "DART", name: "Dartmouth Big Green", color: "#005730", altColor: "#000000", conference: "ivy", division: "Ivy League" },
	{ id: "108", abbr: "HARV", name: "Harvard Crimson", color: "#990000", altColor: "#dbdbdb", conference: "ivy", division: "Ivy League" },
	{ id: "219", abbr: "PENN", name: "Pennsylvania Quakers", color: "#082a74", altColor: "#a6163d", conference: "ivy", division: "Ivy League" },
	{ id: "163", abbr: "PRIN", name: "Princeton Tigers", color: "#000000", altColor: "#ff6000", conference: "ivy", division: "Ivy League" },
	{ id: "43", abbr: "YALE", name: "Yale Bulldogs", color: "#004a81", altColor: "#286dc0", conference: "ivy", division: "Ivy League" },
	{ id: "2837", abbr: "ETAM", name: "East Texas A&M Lions", color: "#000000", altColor: "#f5faf8", conference: "land", division: "Southland Conference" },
	{ id: "2277", abbr: "HCU", name: "Houston Christian Huskies", color: "#00539c", altColor: "#f5faf8", conference: "land", division: "Southland Conference" },
	{ id: "2916", abbr: "UIW", name: "Incarnate Word Cardinals", color: "#000000", altColor: "#080808", conference: "land", division: "Southland Conference" },
	{ id: "2443", abbr: "NOLA", name: "LSU New Orleans Privateers", color: "#005da6", altColor: "#a2a9ae", conference: "land", division: "Southland Conference" },
	{ id: "2320", abbr: "LAM", name: "Lamar Cardinals", color: "#000000", altColor: "#ebebeb", conference: "land", division: "Southland Conference" },
	{ id: "2377", abbr: "MCN", name: "McNeese Cowboys", color: "#00529c", altColor: "#ffd204", conference: "land", division: "Southland Conference" },
	{ id: "2447", abbr: "NICH", name: "Nicholls Colonels", color: "#c41230", altColor: "#f0f0f0", conference: "land", division: "Southland Conference" },
	{ id: "2466", abbr: "NWST", name: "Northwestern State Demons", color: "#492f91", altColor: "#ed6118", conference: "land", division: "Southland Conference" },
	{ id: "2545", abbr: "SELA", name: "SE Louisiana Lions", color: "#215732", altColor: "#ffc72c", conference: "land", division: "Southland Conference" },
	{ id: "2617", abbr: "SFA", name: "Stephen F. Austin Lumberjacks", color: "#393996", altColor: "#bec0c2", conference: "land", division: "Southland Conference" },
	{ id: "357", abbr: "AMCC", name: "Texas A&M-Corpus Christi Islanders", color: "#0067c5", altColor: "#007f3e", conference: "land", division: "Southland Conference" },
	{ id: "292", abbr: "RGV", name: "UT Rio Grande Valley Vaqueros", color: "#dc6000", altColor: "#e1732d", conference: "land", division: "Southland Conference" },
	{ id: "2154", abbr: "COPP", name: "Coppin State Eagles", color: "#2e3192", altColor: "#ffd204", conference: "meac", division: "Mid-Eastern Athletic Conference" },
	{ id: "2169", abbr: "DSU", name: "Delaware State Hornets", color: "#009cdb", altColor: "#d51c28", conference: "meac", division: "Mid-Eastern Athletic Conference" },
	{ id: "47", abbr: "HOW", name: "Howard Bison", color: "#003a63", altColor: "#e51937", conference: "meac", division: "Mid-Eastern Athletic Conference" },
	{ id: "2379", abbr: "UMES", name: "Maryland Eastern Shore Hawks", color: "#5c2301", altColor: "#b5b7ba", conference: "meac", division: "Mid-Eastern Athletic Conference" },
	{ id: "2415", abbr: "MORG", name: "Morgan State Bears", color: "#014786", altColor: "#f47937", conference: "meac", division: "Mid-Eastern Athletic Conference" },
	{ id: "2450", abbr: "NORF", name: "Norfolk State Spartans", color: "#0c8968", altColor: "#fdb813", conference: "meac", division: "Mid-Eastern Athletic Conference" },
	{ id: "2428", abbr: "NCCU", name: "North Carolina Central Eagles", color: "#880023", altColor: "#c2c3c0", conference: "meac", division: "Mid-Eastern Athletic Conference" },
	{ id: "2569", abbr: "SCST", name: "South Carolina State Bulldogs", color: "#7d1315", altColor: "#104897", conference: "meac", division: "Mid-Eastern Athletic Conference" },
	{ id: "2006", abbr: "AKR", name: "Akron Zips", color: "#041e42", altColor: "#c5b783", conference: "midam", division: "Mid-American Conference" },
	{ id: "2050", abbr: "BALL", name: "Ball State Cardinals", color: "#ba0c2f", altColor: "#ffffff", conference: "midam", division: "Mid-American Conference" },
	{ id: "189", abbr: "BGSU", name: "Bowling Green Falcons", color: "#fd5000", altColor: "#4f2c1d", conference: "midam", division: "Mid-American Conference" },
	{ id: "2084", abbr: "BUF", name: "Buffalo Bulls", color: "#005bbb", altColor: "#ffffff", conference: "midam", division: "Mid-American Conference" },
	{ id: "2117", abbr: "CMU", name: "Central Michigan Chippewas", color: "#4c0027", altColor: "#fbab18", conference: "midam", division: "Mid-American Conference" },
	{ id: "2199", abbr: "EMU", name: "Eastern Michigan Eagles", color: "#006938", altColor: "#ffffff", conference: "midam", division: "Mid-American Conference" },
	{ id: "2309", abbr: "KENT", name: "Kent State Golden Flashes", color: "#002664", altColor: "#eaab00", conference: "midam", division: "Mid-American Conference" },
	{ id: "113", abbr: "MASS", name: "Massachusetts Minutemen", color: "#881c1c", altColor: "#ffffff", conference: "midam", division: "Mid-American Conference" },
	{ id: "193", abbr: "M-OH", name: "Miami (OH) RedHawks", color: "#c41230", altColor: "#ffffff", conference: "midam", division: "Mid-American Conference" },
	{ id: "2459", abbr: "NIU", name: "Northern Illinois Huskies", color: "#c8102e", altColor: "#000000", conference: "midam", division: "Mid-American Conference" },
	{ id: "195", abbr: "OHIO", name: "Ohio Bobcats", color: "#154734", altColor: "#ffffff", conference: "midam", division: "Mid-American Conference" },
	{ id: "2649", abbr: "TOL", name: "Toledo Rockets", color: "#0b2240", altColor: "#ffcd00", conference: "midam", division: "Mid-American Conference" },
	{ id: "2711", abbr: "WMU", name: "Western Michigan Broncos", color: "#532e1f", altColor: "#f1c500", conference: "midam", division: "Mid-American Conference" },
	{ id: "2057", abbr: "BEL", name: "Belmont Bruins", color: "#182142", altColor: "#c9262d", conference: "mvc", division: "Missouri Valley Conference" },
	{ id: "71", abbr: "BRAD", name: "Bradley Braves", color: "#b70002", altColor: "#c0c0c0", conference: "mvc", division: "Missouri Valley Conference" },
	{ id: "2181", abbr: "DRKE", name: "Drake Bulldogs", color: "#005596", altColor: "#bec0c2", conference: "mvc", division: "Missouri Valley Conference" },
	{ id: "339", abbr: "EVAN", name: "Evansville Purple Aces", color: "#663399", altColor: "#ef6f00", conference: "mvc", division: "Missouri Valley Conference" },
	{ id: "2287", abbr: "ILST", name: "Illinois State Redbirds", color: "#ce1126", altColor: "#ffe716", conference: "mvc", division: "Missouri Valley Conference" },
	{ id: "282", abbr: "INST", name: "Indiana State Sycamores", color: "#00669a", altColor: "#f0f0f0", conference: "mvc", division: "Missouri Valley Conference" },
	{ id: "93", abbr: "MUR", name: "Murray State Racers", color: "#002148", altColor: "#000e00", conference: "mvc", division: "Missouri Valley Conference" },
	{ id: "2460", abbr: "UNI", name: "Northern Iowa Panthers", color: "#473282", altColor: "#ffffff", conference: "mvc", division: "Missouri Valley Conference" },
	{ id: "79", abbr: "SIU", name: "Southern Illinois Salukis", color: "#85283d", altColor: "#c2c3c0", conference: "mvc", division: "Missouri Valley Conference" },
	{ id: "82", abbr: "UIC", name: "UIC Flames", color: "#001e62", altColor: "#d50032", conference: "mvc", division: "Missouri Valley Conference" },
	{ id: "2674", abbr: "VAL", name: "Valparaiso Beacons", color: "#794500", altColor: "#f5faf8", conference: "mvc", division: "Missouri Valley Conference" },
	{ id: "2005", abbr: "AF", name: "Air Force Falcons", color: "#003594", altColor: "#ffffff", conference: "mwest", division: "Mountain West Conference" },
	{ id: "68", abbr: "BOIS", name: "Boise State Broncos", color: "#0033a0", altColor: "#d64309", conference: "mwest", division: "Mountain West Conference" },
	{ id: "36", abbr: "CSU", name: "Colorado State Rams", color: "#004c23", altColor: "#c8c372", conference: "mwest", division: "Mountain West Conference" },
	{ id: "278", abbr: "FRES", name: "Fresno State Bulldogs", color: "#b1102b", altColor: "#13284c", conference: "mwest", division: "Mountain West Conference" },
	{ id: "2253", abbr: "GCU", name: "Grand Canyon Lopes", color: "#522398", altColor: "#ffffff", conference: "mwest", division: "Mountain West Conference" },
	{ id: "2440", abbr: "NEV", name: "Nevada Wolf Pack", color: "#041e42", altColor: "#8a8d8f", conference: "mwest", division: "Mountain West Conference" },
	{ id: "167", abbr: "UNM", name: "New Mexico Lobos", color: "#ba0c2f", altColor: "#a7a8aa", conference: "mwest", division: "Mountain West Conference" },
	{ id: "21", abbr: "SDSU", name: "San Diego State Aztecs", color: "#a6192e", altColor: "#000000", conference: "mwest", division: "Mountain West Conference" },
	{ id: "23", abbr: "SJSU", name: "San José State Spartans", color: "#0038a8", altColor: "#ffb81a", conference: "mwest", division: "Mountain West Conference" },
	{ id: "2439", abbr: "UNLV", name: "UNLV Rebels", color: "#cf0a2c", altColor: "#cac8c8", conference: "mwest", division: "Mountain West Conference" },
	{ id: "328", abbr: "USU", name: "Utah State Aggies", color: "#0f2439", altColor: "#ffffff", conference: "mwest", division: "Mountain West Conference" },
	{ id: "2751", abbr: "WYO", name: "Wyoming Cowboys", color: "#492f24", altColor: "#ffc425", conference: "mwest", division: "Mountain West Conference" },
	{ id: "2115", abbr: "CCSU", name: "Central Connecticut Blue Devils", color: "#1b49a2", altColor: "#d1d5d8", conference: "neast", division: "Northeast Conference" },
	{ id: "2130", abbr: "CHST", name: "Chicago State Cougars", color: "#006700", altColor: "#f5faf8", conference: "neast", division: "Northeast Conference" },
	{ id: "161", abbr: "FDU", name: "Fairleigh Dickinson Knights", color: "#72293c", altColor: "#28334a", conference: "neast", division: "Northeast Conference" },
	{ id: "2330", abbr: "LEM", name: "Le Moyne Dolphins", color: "#1b1f27", altColor: "#f5faf8", conference: "neast", division: "Northeast Conference" },
	{ id: "112358", abbr: "LIU", name: "Long Island University Sharks", color: "#50c9f7", altColor: "#ffbf00", conference: "neast", division: "Northeast Conference" },
	{ id: "2385", abbr: "MERC", name: "Mercyhurst Lakers", color: "#000000", altColor: "#f5faf8", conference: "neast", division: "Northeast Conference" },
	{ id: "2441", abbr: "NHVN", name: "New Haven Chargers", color: "#041e42", altColor: "#ffc425", conference: "neast", division: "Northeast Conference" },
	{ id: "284", abbr: "STO", name: "Stonehill Skyhawks", color: "#000000", altColor: "#f5faf8", conference: "neast", division: "Northeast Conference" },
	{ id: "2681", abbr: "WAG", name: "Wagner Seahawks", color: "#00483a", altColor: "#ffffff", conference: "neast", division: "Northeast Conference" },
	{ id: "2197", abbr: "EIU", name: "Eastern Illinois Panthers", color: "#000000", altColor: "#bebab9", conference: "ovc", division: "Ohio Valley Conference" },
	{ id: "2031", abbr: "LR", name: "Little Rock Trojans", color: "#ad0000", altColor: "#898d8f", conference: "ovc", division: "Ohio Valley Conference" },
	{ id: "2413", abbr: "MORE", name: "Morehead State Eagles", color: "#094fa3", altColor: "#fed91a", conference: "ovc", division: "Ohio Valley Conference" },
	{ id: "2565", abbr: "SIUE", name: "SIU Edwardsville Cougars", color: "#eb1c23", altColor: "#080808", conference: "ovc", division: "Ohio Valley Conference" },
	{ id: "2546", abbr: "SEMO", name: "Southeast Missouri State Redhawks", color: "#c8102e", altColor: "#000000", conference: "ovc", division: "Ohio Valley Conference" },
	{ id: "2634", abbr: "TNST", name: "Tennessee State Tigers", color: "#171796", altColor: "#f0f0f0", conference: "ovc", division: "Ohio Valley Conference" },
	{ id: "2635", abbr: "TNTC", name: "Tennessee Tech Golden Eagles", color: "#5a4099", altColor: "#ffde00", conference: "ovc", division: "Ohio Valley Conference" },
	{ id: "2630", abbr: "UTM", name: "UT Martin Skyhawks", color: "#ff6700", altColor: "#102a5c", conference: "ovc", division: "Ohio Valley Conference" },
	{ id: "2710", abbr: "WIU", name: "Western Illinois Leathernecks", color: "#4e1e8a", altColor: "#ffc90a", conference: "ovc", division: "Ohio Valley Conference" },
	{ id: "44", abbr: "AMER", name: "American University Eagles", color: "#c41130", altColor: "#c8102e", conference: "pat", division: "Patriot League" },
	{ id: "349", abbr: "ARMY", name: "Army Black Knights", color: "#000000", altColor: "#d3bc8d", conference: "pat", division: "Patriot League" },
	{ id: "104", abbr: "BU", name: "Boston University Terriers", color: "#cc0000", altColor: "#ffffff", conference: "pat", division: "Patriot League" },
	{ id: "2083", abbr: "BUCK", name: "Bucknell Bison", color: "#000060", altColor: "#00316e", conference: "pat", division: "Patriot League" },
	{ id: "2142", abbr: "COLG", name: "Colgate Raiders", color: "#821019", altColor: "#ffffff", conference: "pat", division: "Patriot League" },
	{ id: "107", abbr: "HC", name: "Holy Cross Crusaders", color: "#582c83", altColor: "#ffffff", conference: "pat", division: "Patriot League" },
	{ id: "322", abbr: "LAF", name: "Lafayette Leopards", color: "#790000", altColor: "#a59474", conference: "pat", division: "Patriot League" },
	{ id: "2329", abbr: "LEH", name: "Lehigh Mountain Hawks", color: "#6c2b2a", altColor: "#b69e70", conference: "pat", division: "Patriot League" },
	{ id: "2352", abbr: "L-MD", name: "Loyola Maryland Greyhounds", color: "#76a7a0", altColor: "#c9cbca", conference: "pat", division: "Patriot League" },
	{ id: "2426", abbr: "NAVY", name: "Navy Midshipmen", color: "#00225b", altColor: "#b5a67c", conference: "pat", division: "Patriot League" },
	{ id: "333", abbr: "ALA", name: "Alabama Crimson Tide", color: "#9e1b32", altColor: "#ffffff", conference: "sec", division: "Southeastern Conference" },
	{ id: "8", abbr: "ARK", name: "Arkansas Razorbacks", color: "#a32136", altColor: "#ffffff", conference: "sec", division: "Southeastern Conference" },
	{ id: "2", abbr: "AUB", name: "Auburn Tigers", color: "#002b5c", altColor: "#f26522", conference: "sec", division: "Southeastern Conference" },
	{ id: "57", abbr: "FLA", name: "Florida Gators", color: "#0021a5", altColor: "#fa4616", conference: "sec", division: "Southeastern Conference" },
	{ id: "61", abbr: "UGA", name: "Georgia Bulldogs", color: "#ba0c2f", altColor: "#2c2a29", conference: "sec", division: "Southeastern Conference" },
	{ id: "96", abbr: "UK", name: "Kentucky Wildcats", color: "#0033a0", altColor: "#ffffff", conference: "sec", division: "Southeastern Conference" },
	{ id: "99", abbr: "LSU", name: "LSU Tigers", color: "#461d76", altColor: "#fdd023", conference: "sec", division: "Southeastern Conference" },
	{ id: "344", abbr: "MSST", name: "Mississippi State Bulldogs", color: "#5d1725", altColor: "#c1c6c8", conference: "sec", division: "Southeastern Conference" },
	{ id: "142", abbr: "MIZ", name: "Missouri Tigers", color: "#f1b82d", altColor: "#000000", conference: "sec", division: "Southeastern Conference" },
	{ id: "201", abbr: "OU", name: "Oklahoma Sooners", color: "#990000", altColor: "#ffffff", conference: "sec", division: "Southeastern Conference" },
	{ id: "145", abbr: "MISS", name: "Ole Miss Rebels", color: "#13294b", altColor: "#cf142b", conference: "sec", division: "Southeastern Conference" },
	{ id: "2579", abbr: "SC", name: "South Carolina Gamecocks", color: "#73000a", altColor: "#000000", conference: "sec", division: "Southeastern Conference" },
	{ id: "2633", abbr: "TENN", name: "Tennessee Volunteers", color: "#ff8200", altColor: "#ffffff", conference: "sec", division: "Southeastern Conference" },
	{ id: "245", abbr: "TA&M", name: "Texas A&M Aggies", color: "#500000", altColor: "#ffffff", conference: "sec", division: "Southeastern Conference" },
	{ id: "251", abbr: "TEX", name: "Texas Longhorns", color: "#af5c37", altColor: "#ffffff", conference: "sec", division: "Southeastern Conference" },
	{ id: "238", abbr: "VAN", name: "Vanderbilt Commodores", color: "#000000", altColor: "#cfae70", conference: "sec", division: "Southeastern Conference" },
	{ id: "236", abbr: "UTC", name: "Chattanooga Mocs", color: "#00386b", altColor: "#dca71d", conference: "south", division: "Southern Conference" },
	{ id: "2193", abbr: "ETSU", name: "East Tennessee State Buccaneers", color: "#002d61", altColor: "#ffc423", conference: "south", division: "Southern Conference" },
	{ id: "231", abbr: "FUR", name: "Furman Paladins", color: "#582c83", altColor: "#ffffff", conference: "south", division: "Southern Conference" },
	{ id: "2382", abbr: "MER", name: "Mercer Bears", color: "#ff7f29", altColor: "#080808", conference: "south", division: "Southern Conference" },
	{ id: "2535", abbr: "SAM", name: "Samford Bulldogs", color: "#005485", altColor: "#bc0023", conference: "south", division: "Southern Conference" },
	{ id: "2643", abbr: "CIT", name: "The Citadel Bulldogs", color: "#7badd3", altColor: "#002856", conference: "south", division: "Southern Conference" },
	{ id: "2430", abbr: "UNCG", name: "UNC Greensboro Spartans", color: "#003559", altColor: "#ffd90a", conference: "south", division: "Southern Conference" },
	{ id: "2678", abbr: "VMI", name: "VMI Keydets", color: "#ae122a", altColor: "#ffd619", conference: "south", division: "Southern Conference" },
	{ id: "2717", abbr: "WCU", name: "Western Carolina Catamounts", color: "#492f91", altColor: "#bf9e70", conference: "south", division: "Southern Conference" },
	{ id: "2747", abbr: "WOF", name: "Wofford Terriers", color: "#533b22", altColor: "#f0f0f0", conference: "south", division: "Southern Conference" },
	{ id: "2172", abbr: "DEN", name: "Denver Pioneers", color: "#98002e", altColor: "#a8996e", conference: "summ", division: "Summit League" },
	{ id: "140", abbr: "KC", name: "Kansas City Roos", color: "#004b87", altColor: "#ffc72c", conference: "summ", division: "Summit League" },
	{ id: "155", abbr: "UND", name: "North Dakota Fighting Hawks", color: "#00a26b", altColor: "#c2c3c0", conference: "summ", division: "Summit League" },
	{ id: "2449", abbr: "NDSU", name: "North Dakota State Bison", color: "#01402a", altColor: "#ffffff", conference: "summ", division: "Summit League" },
	{ id: "2437", abbr: "OMA", name: "Omaha Mavericks", color: "#e3193e", altColor: "#474648", conference: "summ", division: "Summit League" },
	{ id: "198", abbr: "ORU", name: "Oral Roberts Golden Eagles", color: "#002462", altColor: "#dac792", conference: "summ", division: "Summit League" },
	{ id: "233", abbr: "SDAK", name: "South Dakota Coyotes", color: "#cd1241", altColor: "#f0f0f0", conference: "summ", division: "Summit League" },
	{ id: "2571", abbr: "SDST", name: "South Dakota State Jackrabbits", color: "#0033a0", altColor: "#ffd100", conference: "summ", division: "Summit League" },
	{ id: "2900", abbr: "STMN", name: "St. Thomas Tommies", color: "#000000", altColor: "#f5faf8", conference: "summ", division: "Summit League" },
	{ id: "2010", abbr: "AAMU", name: "Alabama A&M Bulldogs", color: "#790000", altColor: "#ffffff", conference: "swac", division: "Southwestern Athletic Conference" },
	{ id: "2011", abbr: "ALST", name: "Alabama State Hornets", color: "#e9a900", altColor: "#0a0a0a", conference: "swac", division: "Southwestern Athletic Conference" },
	{ id: "2016", abbr: "ALCN", name: "Alcorn State Braves", color: "#4b0058", altColor: "#46166a", conference: "swac", division: "Southwestern Athletic Conference" },
	{ id: "2029", abbr: "UAPB", name: "Arkansas-Pine Bluff Golden Lions", color: "#e0aa0f", altColor: "#eaaa00", conference: "swac", division: "Southwestern Athletic Conference" },
	{ id: "2065", abbr: "BCU", name: "Bethune-Cookman Wildcats", color: "#7b1831", altColor: "#e9aa12", conference: "swac", division: "Southwestern Athletic Conference" },
	{ id: "50", abbr: "FAMU", name: "Florida A&M Rattlers", color: "#f89728", altColor: "#00843d", conference: "swac", division: "Southwestern Athletic Conference" },
	{ id: "2755", abbr: "GRAM", name: "Grambling Tigers", color: "#ee8601", altColor: "#ffd10a", conference: "swac", division: "Southwestern Athletic Conference" },
	{ id: "2296", abbr: "JKST", name: "Jackson State Tigers", color: "#123297", altColor: "#b5b7ba", conference: "swac", division: "Southwestern Athletic Conference" },
	{ id: "2400", abbr: "MVSU", name: "Mississippi Valley State Delta Devils", color: "#005328", altColor: "#cf2d34", conference: "swac", division: "Southwestern Athletic Conference" },
	{ id: "2504", abbr: "PV", name: "Prairie View A&M Panthers", color: "#582c83", altColor: "#eaaa00", conference: "swac", division: "Southwestern Athletic Conference" },
	{ id: "2582", abbr: "SOU", name: "Southern Jaguars", color: "#004b97", altColor: "#ffc82d", conference: "swac", division: "Southwestern Athletic Conference" },
	{ id: "2640", abbr: "TXSO", name: "Texas Southern Tigers", color: "#860038", altColor: "#ffffff", conference: "swac", division: "Southwestern Athletic Conference" },
	{ id: "48", abbr: "DEL", name: "Delaware Blue Hens", color: "#00539f", altColor: "#ffd200", conference: "usa", division: "Conference USA" },
	{ id: "2229", abbr: "FIU", name: "Florida International Panthers", color: "#091f3f", altColor: "#c3993f", conference: "usa", division: "Conference USA" },
	{ id: "55", abbr: "JXST", name: "Jacksonville State Gamecocks", color: "#cc0000", altColor: "#000000", conference: "usa", division: "Conference USA" },
	{ id: "338", abbr: "KENN", name: "Kennesaw State Owls", color: "#fdbb30", altColor: "#0b1315", conference: "usa", division: "Conference USA" },
	{ id: "2335", abbr: "LIB", name: "Liberty Flames", color: "#0a254e", altColor: "#b72025", conference: "usa", division: "Conference USA" },
	{ id: "2348", abbr: "LT", name: "Louisiana Tech Bulldogs", color: "#003087", altColor: "#cb333b", conference: "usa", division: "Conference USA" },
	{ id: "2393", abbr: "MTSU", name: "Middle Tennessee Blue Raiders", color: "#036eb7", altColor: "#ffffff", conference: "usa", division: "Conference USA" },
	{ id: "2623", abbr: "MOST", name: "Missouri State Bears", color: "#5e0009", altColor: "#ffffff", conference: "usa", division: "Conference USA" },
	{ id: "166", abbr: "NMSU", name: "New Mexico State Aggies", color: "#7e141b", altColor: "#231f20", conference: "usa", division: "Conference USA" },
	{ id: "2534", abbr: "SHSU", name: "Sam Houston Bearkats", color: "#f56423", altColor: "#ffffff", conference: "usa", division: "Conference USA" },
	{ id: "2638", abbr: "UTEP", name: "UTEP Miners", color: "#ff8200", altColor: "#041e42", conference: "usa", division: "Conference USA" },
	{ id: "98", abbr: "WKU", name: "Western Kentucky Hilltoppers", color: "#e13a3e", altColor: "#ffffff", conference: "usa", division: "Conference USA" },
	{ id: "2250", abbr: "GONZ", name: "Gonzaga Bulldogs", color: "#041e42", altColor: "#c8102e", conference: "wcc", division: "West Coast Conference" },
	{ id: "2351", abbr: "LMU", name: "Loyola Marymount Lions", color: "#880029", altColor: "#00345b", conference: "wcc", division: "West Coast Conference" },
	{ id: "204", abbr: "ORST", name: "Oregon State Beavers", color: "#dc4405", altColor: "#000000", conference: "wcc", division: "West Coast Conference" },
	{ id: "279", abbr: "PAC", name: "Pacific Tigers", color: "#f47820", altColor: "#c2c3c0", conference: "wcc", division: "West Coast Conference" },
	{ id: "2492", abbr: "PEPP", name: "Pepperdine Waves", color: "#003a72", altColor: "#dc762f", conference: "wcc", division: "West Coast Conference" },
	{ id: "2501", abbr: "PORT", name: "Portland Pilots", color: "#330072", altColor: "#a8b3ba", conference: "wcc", division: "West Coast Conference" },
	{ id: "2608", abbr: "SMC", name: "Saint Mary's Gaels", color: "#d80024", altColor: "#003057", conference: "wcc", division: "West Coast Conference" },
	{ id: "301", abbr: "USD", name: "San Diego Toreros", color: "#2f99d4", altColor: "#2f99d4", conference: "wcc", division: "West Coast Conference" },
	{ id: "2539", abbr: "SF", name: "San Francisco Dons", color: "#005a36", altColor: "#ffffff", conference: "wcc", division: "West Coast Conference" },
	{ id: "2541", abbr: "SCU", name: "Santa Clara Broncos", color: "#690b0b", altColor: "#101010", conference: "wcc", division: "West Coast Conference" },
	{ id: "2547", abbr: "SEA", name: "Seattle U Redhawks", color: "#bf2e1a", altColor: "#c2c3c0", conference: "wcc", division: "West Coast Conference" },
	{ id: "265", abbr: "WSU", name: "Washington State Cougars", color: "#a60f2d", altColor: "#4d4d4d", conference: "wcc", division: "West Coast Conference" },
];
