/**
 * COLLEGE-FOOTBALL teams, generated from ESPN by plugins/_shared/scripts/gen_teams.py.
 * Do not hand edit: rerun the script to refresh.
 *
 * Colours are the official team colours, used as the key's colour spine. They are the only
 * team branding this product ever renders. No logos, crests or wordmarks, anywhere.
 */
import type { SportTeam } from "../../../_shared/src/sport";

export const CFB_TEAMS: SportTeam[] = [
	{ id: "349", abbr: "ARMY", name: "Army Black Knights", color: "#000000", altColor: "#d3bc8d", conference: "American", division: "American Conference" },
	{ id: "2429", abbr: "CLT", name: "Charlotte 49ers", color: "#005035", altColor: "#a49665", conference: "American", division: "American Conference" },
	{ id: "151", abbr: "ECU", name: "East Carolina Pirates", color: "#582c83", altColor: "#ffc72c", conference: "American", division: "American Conference" },
	{ id: "2226", abbr: "FAU", name: "Florida Atlantic Owls", color: "#003366", altColor: "#cc0000", conference: "American", division: "American Conference" },
	{ id: "235", abbr: "MEM", name: "Memphis Tigers", color: "#004991", altColor: "#8e908f", conference: "American", division: "American Conference" },
	{ id: "2426", abbr: "NAVY", name: "Navy Midshipmen", color: "#00225b", altColor: "#b5a67c", conference: "American", division: "American Conference" },
	{ id: "249", abbr: "UNT", name: "North Texas Mean Green", color: "#068f33", altColor: "#ffffff", conference: "American", division: "American Conference" },
	{ id: "242", abbr: "RICE", name: "Rice Owls", color: "#00205b", altColor: "#c1c6c8", conference: "American", division: "American Conference" },
	{ id: "58", abbr: "USF", name: "South Florida Bulls", color: "#006747", altColor: "#cfc493", conference: "American", division: "American Conference" },
	{ id: "218", abbr: "TEM", name: "Temple Owls", color: "#a41e35", altColor: "#ffffff", conference: "American", division: "American Conference" },
	{ id: "202", abbr: "TLSA", name: "Tulsa Golden Hurricane", color: "#003595", altColor: "#d0b787", conference: "American", division: "American Conference" },
	{ id: "5", abbr: "UAB", name: "UAB Blazers", color: "#1a5632", altColor: "#fdb913", conference: "American", division: "American Conference" },
	{ id: "103", abbr: "BC", name: "Boston College Eagles", color: "#8c2232", altColor: "#dbcca6", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "25", abbr: "CAL", name: "California Golden Bears", color: "#041e42", altColor: "#ffc72c", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "228", abbr: "CLEM", name: "Clemson Tigers", color: "#f56600", altColor: "#ffffff", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "150", abbr: "DUKE", name: "Duke Blue Devils", color: "#00539b", altColor: "#ffffff", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "52", abbr: "FSU", name: "Florida State Seminoles", color: "#782f40", altColor: "#ceb888", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "59", abbr: "GT", name: "Georgia Tech Yellow Jackets", color: "#b3a369", altColor: "#ffffff", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "97", abbr: "LOU", name: "Louisville Cardinals", color: "#c9001f", altColor: "#ffffff", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "2390", abbr: "MIA", name: "Miami Hurricanes", color: "#f47423", altColor: "#035131", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "152", abbr: "NCSU", name: "NC State Wolfpack", color: "#cc0000", altColor: "#ffffff", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "153", abbr: "UNC", name: "North Carolina Tar Heels", color: "#7bafd4", altColor: "#13294b", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "221", abbr: "PITT", name: "Pittsburgh Panthers", color: "#003594", altColor: "#ffb81c", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "24", abbr: "STAN", name: "Stanford Cardinal", color: "#8c1515", altColor: "#ffffff", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "183", abbr: "SYR", name: "Syracuse Orange", color: "#000e54", altColor: "#ff431b", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "258", abbr: "UVA", name: "Virginia Cavaliers", color: "#232d4b", altColor: "#f84c1e", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "259", abbr: "VT", name: "Virginia Tech Hokies", color: "#6a2c3e", altColor: "#cf4520", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "154", abbr: "WAKE", name: "Wake Forest Demon Deacons", color: "#ceb888", altColor: "#2c2a29", conference: "acc", division: "Atlantic Coast Conference" },
	{ id: "2026", abbr: "APP", name: "App State Mountaineers", color: "#000000", altColor: "#ffcd00", conference: "belt", division: "Sun Belt - East" },
	{ id: "2032", abbr: "ARST", name: "Arkansas State Red Wolves", color: "#cc092f", altColor: "#000000", conference: "belt", division: "Sun Belt - West" },
	{ id: "324", abbr: "CCU", name: "Coastal Carolina Chanticleers", color: "#006f71", altColor: "#a27752", conference: "belt", division: "Sun Belt - East" },
	{ id: "290", abbr: "GASO", name: "Georgia Southern Eagles", color: "#041e42", altColor: "#a3aaae", conference: "belt", division: "Sun Belt - East" },
	{ id: "2247", abbr: "GAST", name: "Georgia State Panthers", color: "#0039a6", altColor: "#ffffff", conference: "belt", division: "Sun Belt - East" },
	{ id: "256", abbr: "JMU", name: "James Madison Dukes", color: "#450084", altColor: "#cbb677", conference: "belt", division: "Sun Belt - East" },
	{ id: "309", abbr: "UL", name: "Louisiana Ragin' Cajuns", color: "#ce181e", altColor: "#000000", conference: "belt", division: "Sun Belt - West" },
	{ id: "2348", abbr: "LT", name: "Louisiana Tech Bulldogs", color: "#003087", altColor: "#cb333b", conference: "belt", division: "Sun Belt - West" },
	{ id: "276", abbr: "MRSH", name: "Marshall Thundering Herd", color: "#00b140", altColor: "#000000", conference: "belt", division: "Sun Belt - East" },
	{ id: "295", abbr: "ODU", name: "Old Dominion Monarchs", color: "#003768", altColor: "#a1d2f1", conference: "belt", division: "Sun Belt - East" },
	{ id: "6", abbr: "USA", name: "South Alabama Jaguars", color: "#00205b", altColor: "#bf0d3e", conference: "belt", division: "Sun Belt - West" },
	{ id: "2433", abbr: "ULM", name: "UL Monroe Warhawks", color: "#840029", altColor: "#fdb913", conference: "belt", division: "Sun Belt - West" },
	{ id: "356", abbr: "ILL", name: "Illinois Fighting Illini", color: "#ff5f05", altColor: "#13294b", conference: "big10", division: "Big Ten Conference" },
	{ id: "84", abbr: "IU", name: "Indiana Hoosiers", color: "#970310", altColor: "#ffffff", conference: "big10", division: "Big Ten Conference" },
	{ id: "2294", abbr: "IOWA", name: "Iowa Hawkeyes", color: "#231f20", altColor: "#fcd116", conference: "big10", division: "Big Ten Conference" },
	{ id: "120", abbr: "MD", name: "Maryland Terrapins", color: "#ce1126", altColor: "#ffffff", conference: "big10", division: "Big Ten Conference" },
	{ id: "127", abbr: "MSU", name: "Michigan State Spartans", color: "#173f35", altColor: "#ffffff", conference: "big10", division: "Big Ten Conference" },
	{ id: "130", abbr: "MICH", name: "Michigan Wolverines", color: "#00274c", altColor: "#ffcb05", conference: "big10", division: "Big Ten Conference" },
	{ id: "135", abbr: "MINN", name: "Minnesota Golden Gophers", color: "#5e0a2f", altColor: "#fab41c", conference: "big10", division: "Big Ten Conference" },
	{ id: "158", abbr: "NEB", name: "Nebraska Cornhuskers", color: "#e31937", altColor: "#ffffff", conference: "big10", division: "Big Ten Conference" },
	{ id: "77", abbr: "NU", name: "Northwestern Wildcats", color: "#492f92", altColor: "#ffffff", conference: "big10", division: "Big Ten Conference" },
	{ id: "194", abbr: "OSU", name: "Ohio State Buckeyes", color: "#ba0c2f", altColor: "#a8adb4", conference: "big10", division: "Big Ten Conference" },
	{ id: "2483", abbr: "ORE", name: "Oregon Ducks", color: "#00934b", altColor: "#fff41b", conference: "big10", division: "Big Ten Conference" },
	{ id: "213", abbr: "PSU", name: "Penn State Nittany Lions", color: "#061440", altColor: "#ffffff", conference: "big10", division: "Big Ten Conference" },
	{ id: "164", abbr: "RUTG", name: "Rutgers Scarlet Knights", color: "#ce0e2d", altColor: "#ffffff", conference: "big10", division: "Big Ten Conference" },
	{ id: "26", abbr: "UCLA", name: "UCLA Bruins", color: "#2774ae", altColor: "#f2a900", conference: "big10", division: "Big Ten Conference" },
	{ id: "30", abbr: "USC", name: "USC Trojans", color: "#9d2235", altColor: "#ffc72c", conference: "big10", division: "Big Ten Conference" },
	{ id: "264", abbr: "WASH", name: "Washington Huskies", color: "#33006f", altColor: "#e8d3a2", conference: "big10", division: "Big Ten Conference" },
	{ id: "275", abbr: "WIS", name: "Wisconsin Badgers", color: "#a00000", altColor: "#ffffff", conference: "big10", division: "Big Ten Conference" },
	{ id: "9", abbr: "ASU", name: "Arizona State Sun Devils", color: "#ffc627", altColor: "#8c1d40", conference: "big12", division: "Big 12 Conference" },
	{ id: "12", abbr: "ARIZ", name: "Arizona Wildcats", color: "#cc0033", altColor: "#003366", conference: "big12", division: "Big 12 Conference" },
	{ id: "252", abbr: "BYU", name: "BYU Cougars", color: "#0047ba", altColor: "#002e5d", conference: "big12", division: "Big 12 Conference" },
	{ id: "239", abbr: "BAY", name: "Baylor Bears", color: "#154734", altColor: "#ffb81c", conference: "big12", division: "Big 12 Conference" },
	{ id: "2132", abbr: "CIN", name: "Cincinnati Bearcats", color: "#000000", altColor: "#e00122", conference: "big12", division: "Big 12 Conference" },
	{ id: "38", abbr: "COLO", name: "Colorado Buffaloes", color: "#cfb87c", altColor: "#000000", conference: "big12", division: "Big 12 Conference" },
	{ id: "248", abbr: "HOU", name: "Houston Cougars", color: "#c8102e", altColor: "#ffffff", conference: "big12", division: "Big 12 Conference" },
	{ id: "66", abbr: "ISU", name: "Iowa State Cyclones", color: "#ae192d", altColor: "#ffc72a", conference: "big12", division: "Big 12 Conference" },
	{ id: "2305", abbr: "KU", name: "Kansas Jayhawks", color: "#0051ba", altColor: "#e8000d", conference: "big12", division: "Big 12 Conference" },
	{ id: "2306", abbr: "KSU", name: "Kansas State Wildcats", color: "#330a57", altColor: "#e2e3e4", conference: "big12", division: "Big 12 Conference" },
	{ id: "197", abbr: "OKST", name: "Oklahoma State Cowboys", color: "#fe5c00", altColor: "#000000", conference: "big12", division: "Big 12 Conference" },
	{ id: "2116", abbr: "UCF", name: "UCF Knights", color: "#000000", altColor: "#b4a169", conference: "big12", division: "Big 12 Conference" },
	{ id: "254", abbr: "UTAH", name: "Utah Utes", color: "#be0000", altColor: "#ffffff", conference: "big12", division: "Big 12 Conference" },
	{ id: "277", abbr: "WVU", name: "West Virginia Mountaineers", color: "#eaaa00", altColor: "#002855", conference: "big12", division: "Big 12 Conference" },
	{ id: "87", abbr: "ND", name: "Notre Dame Fighting Irish", color: "#062340", altColor: "#c99700", conference: "ind", division: "FBS Independents" },
	{ id: "41", abbr: "CONN", name: "UConn Huskies", color: "#0c2340", altColor: "#a2aaad", conference: "ind", division: "FBS Independents" },
	{ id: "2006", abbr: "AKR", name: "Akron Zips", color: "#041e42", altColor: "#c5b783", conference: "midam", division: "Mid-American Conference" },
	{ id: "2050", abbr: "BALL", name: "Ball State Cardinals", color: "#ba0c2f", altColor: "#ffffff", conference: "midam", division: "Mid-American Conference" },
	{ id: "189", abbr: "BGSU", name: "Bowling Green Falcons", color: "#fd5000", altColor: "#4f2c1d", conference: "midam", division: "Mid-American Conference" },
	{ id: "2084", abbr: "BUF", name: "Buffalo Bulls", color: "#005bbb", altColor: "#ffffff", conference: "midam", division: "Mid-American Conference" },
	{ id: "2117", abbr: "CMU", name: "Central Michigan Chippewas", color: "#4c0027", altColor: "#fbab18", conference: "midam", division: "Mid-American Conference" },
	{ id: "2199", abbr: "EMU", name: "Eastern Michigan Eagles", color: "#006938", altColor: "#ffffff", conference: "midam", division: "Mid-American Conference" },
	{ id: "2309", abbr: "KENT", name: "Kent State Golden Flashes", color: "#002664", altColor: "#eaab00", conference: "midam", division: "Mid-American Conference" },
	{ id: "113", abbr: "MASS", name: "Massachusetts Minutemen", color: "#881c1c", altColor: "#ffffff", conference: "midam", division: "Mid-American Conference" },
	{ id: "193", abbr: "M-OH", name: "Miami (OH) RedHawks", color: "#c41230", altColor: "#ffffff", conference: "midam", division: "Mid-American Conference" },
	{ id: "195", abbr: "OHIO", name: "Ohio Bobcats", color: "#154734", altColor: "#ffffff", conference: "midam", division: "Mid-American Conference" },
	{ id: "16", abbr: "SAC", name: "Sacramento State Hornets", color: "#00573c", altColor: "#cdb97d", conference: "midam", division: "Mid-American Conference" },
	{ id: "2005", abbr: "AF", name: "Air Force Falcons", color: "#003594", altColor: "#ffffff", conference: "mwest", division: "Mountain West Conference" },
	{ id: "62", abbr: "HAW", name: "Hawai'i Rainbow Warriors", color: "#005737", altColor: "#000000", conference: "mwest", division: "Mountain West Conference" },
	{ id: "2440", abbr: "NEV", name: "Nevada Wolf Pack", color: "#041e42", altColor: "#8a8d8f", conference: "mwest", division: "Mountain West Conference" },
	{ id: "167", abbr: "UNM", name: "New Mexico Lobos", color: "#ba0c2f", altColor: "#a7a8aa", conference: "mwest", division: "Mountain West Conference" },
	{ id: "2449", abbr: "NDSU", name: "North Dakota State Bison", color: "#01402a", altColor: "#ffffff", conference: "mwest", division: "Mountain West Conference" },
	{ id: "2459", abbr: "NIU", name: "Northern Illinois Huskies", color: "#c8102e", altColor: "#000000", conference: "mwest", division: "Mountain West Conference" },
	{ id: "23", abbr: "SJSU", name: "San José State Spartans", color: "#0038a8", altColor: "#ffb81a", conference: "mwest", division: "Mountain West Conference" },
	{ id: "2439", abbr: "UNLV", name: "UNLV Rebels", color: "#cf0a2c", altColor: "#cac8c8", conference: "mwest", division: "Mountain West Conference" },
	{ id: "68", abbr: "BOIS", name: "Boise State Broncos", color: "#0033a0", altColor: "#d64309", conference: "pac12", division: "Pac-12 Conference" },
	{ id: "36", abbr: "CSU", name: "Colorado State Rams", color: "#004c23", altColor: "#c8c372", conference: "pac12", division: "Pac-12 Conference" },
	{ id: "278", abbr: "FRES", name: "Fresno State Bulldogs", color: "#b1102b", altColor: "#13284c", conference: "pac12", division: "Pac-12 Conference" },
	{ id: "204", abbr: "ORST", name: "Oregon State Beavers", color: "#dc4405", altColor: "#000000", conference: "pac12", division: "Pac-12 Conference" },
	{ id: "21", abbr: "SDSU", name: "San Diego State Aztecs", color: "#a6192e", altColor: "#000000", conference: "pac12", division: "Pac-12 Conference" },
	{ id: "326", abbr: "TXST", name: "Texas State Bobcats", color: "#501214", altColor: "#6a5638", conference: "pac12", division: "Pac-12 Conference" },
	{ id: "328", abbr: "USU", name: "Utah State Aggies", color: "#0f2439", altColor: "#ffffff", conference: "pac12", division: "Pac-12 Conference" },
	{ id: "265", abbr: "WSU", name: "Washington State Cougars", color: "#a60f2d", altColor: "#4d4d4d", conference: "pac12", division: "Pac-12 Conference" },
	{ id: "333", abbr: "ALA", name: "Alabama Crimson Tide", color: "#9e1b32", altColor: "#ffffff", conference: "sec", division: "Southeastern Conference" },
	{ id: "8", abbr: "ARK", name: "Arkansas Razorbacks", color: "#a32136", altColor: "#ffffff", conference: "sec", division: "Southeastern Conference" },
	{ id: "2", abbr: "AUB", name: "Auburn Tigers", color: "#002b5c", altColor: "#f26522", conference: "sec", division: "Southeastern Conference" },
	{ id: "57", abbr: "FLA", name: "Florida Gators", color: "#0021a5", altColor: "#fa4616", conference: "sec", division: "Southeastern Conference" },
	{ id: "61", abbr: "UGA", name: "Georgia Bulldogs", color: "#ba0c2f", altColor: "#2c2a29", conference: "sec", division: "Southeastern Conference" },
	{ id: "96", abbr: "UK", name: "Kentucky Wildcats", color: "#0033a0", altColor: "#ffffff", conference: "sec", division: "Southeastern Conference" },
	{ id: "99", abbr: "LSU", name: "LSU Tigers", color: "#461d76", altColor: "#fdd023", conference: "sec", division: "Southeastern Conference" },
	{ id: "344", abbr: "MSST", name: "Mississippi State Bulldogs", color: "#5d1725", altColor: "#c1c6c8", conference: "sec", division: "Southeastern Conference" },
	{ id: "142", abbr: "MIZ", name: "Missouri Tigers", color: "#f1b82d", altColor: "#000000", conference: "sec", division: "Southeastern Conference" },
	{ id: "201", abbr: "OU", name: "Oklahoma Sooners", color: "#990000", altColor: "#ffffff", conference: "sec", division: "Southeastern Conference" },
	{ id: "145", abbr: "MISS", name: "Ole Miss Rebels", color: "#13294b", altColor: "#cf142b", conference: "sec", division: "Southeastern Conference" },
	{ id: "2633", abbr: "TENN", name: "Tennessee Volunteers", color: "#ff8200", altColor: "#ffffff", conference: "sec", division: "Southeastern Conference" },
	{ id: "245", abbr: "TA&M", name: "Texas A&M Aggies", color: "#500000", altColor: "#ffffff", conference: "sec", division: "Southeastern Conference" },
	{ id: "251", abbr: "TEX", name: "Texas Longhorns", color: "#af5c37", altColor: "#ffffff", conference: "sec", division: "Southeastern Conference" },
	{ id: "238", abbr: "VAN", name: "Vanderbilt Commodores", color: "#000000", altColor: "#cfae70", conference: "sec", division: "Southeastern Conference" },
	{ id: "48", abbr: "DEL", name: "Delaware Blue Hens", color: "#00539f", altColor: "#ffd200", conference: "usa", division: "Conference USA" },
	{ id: "2229", abbr: "FIU", name: "Florida International Panthers", color: "#091f3f", altColor: "#c3993f", conference: "usa", division: "Conference USA" },
	{ id: "55", abbr: "JXST", name: "Jacksonville State Gamecocks", color: "#cc0000", altColor: "#000000", conference: "usa", division: "Conference USA" },
	{ id: "338", abbr: "KENN", name: "Kennesaw State Owls", color: "#fdbb30", altColor: "#0b1315", conference: "usa", division: "Conference USA" },
	{ id: "2335", abbr: "LIB", name: "Liberty Flames", color: "#0a254e", altColor: "#b72025", conference: "usa", division: "Conference USA" },
	{ id: "2393", abbr: "MTSU", name: "Middle Tennessee Blue Raiders", color: "#036eb7", altColor: "#ffffff", conference: "usa", division: "Conference USA" },
	{ id: "166", abbr: "NMSU", name: "New Mexico State Aggies", color: "#7e141b", altColor: "#231f20", conference: "usa", division: "Conference USA" },
	{ id: "98", abbr: "WKU", name: "Western Kentucky Hilltoppers", color: "#e13a3e", altColor: "#ffffff", conference: "usa", division: "Conference USA" },
];
