import test from "node:test";import assert from "node:assert/strict";
import {UUID,KINDS,settingsFor,optionsFor,commandFor,favoriteCommands,currentTarget,observed} from "../src/state.js";
import {renderKey,viewFor,neoFeedback} from "../src/render.js";
const hue={id:"hue:light:001",name:"Desk",provider:"hue",kind:"light",on:true,brightness:40,reachable:true,capabilities:{power:true,brightness:true,color:true,temperature:true},temperatureRange:[2200,6500],favorite:true};
const govee={id:"govee:lan:001",name:"Desk",provider:"govee",kind:"light",on:false,brightness:80,reachable:true,capabilities:{power:true,brightness:true,color:true,temperature:false},favorite:true};
const room={id:"hue:room:001",name:"Office",provider:"hue",kind:"room",on:true,capabilities:{power:true,brightness:true},favorite:false};
const scene={id:"hue:scene:001",name:"Relax",provider:"hue",kind:"scene",capabilities:{scene:true},favorite:true};
const snap={targets:[hue,govee,room,scene]};
test("stable unique UUIDs",()=>assert.equal(new Set(Object.values(UUID)).size,Object.keys(UUID).length));
test("identity never uses duplicate names",()=>{assert.equal(currentTarget(snap,govee.id).provider,"govee");assert.equal(currentTarget(snap,"Desk"),null);});
test("capability-aware per provider",()=>{assert.equal(optionsFor(snap,"tone",{toneMode:"temperature"}).length,1);assert.equal(optionsFor(snap,"scene").length,1);assert.equal(optionsFor(snap,"power").length,3);});
test("unknown ids not silently replaced",()=>assert.equal(currentTarget(snap,"gone"),null));
test("power toggles live state",()=>assert.deepEqual(commandFor("power",hue,settingsFor()),{command:"power",id:hue.id,value:false}));
test("Govee RGB uses capability only",()=>{const c=commandFor("tone",govee,settingsFor({hex:"#102030"},"tone"));assert.deepEqual([c.r,c.g,c.b],[16,32,48]);});
test("Govee unsupported temperature fails",()=>assert.throws(()=>commandFor("tone",govee,settingsFor({toneMode:"temperature"},"tone")),/does not support/));
test("temperature respects Hue bounds",()=>assert.equal(commandFor("tone",hue,settingsFor({toneMode:"temperature",kelvin:9000},"tone")).value,6500));
test("scenes have stable ID",()=>assert.equal(commandFor("scene",scene,settingsFor()).sceneId,scene.id));
test("power scene unsupported",()=>assert.throws(()=>commandFor("power",scene,settingsFor())));
test("mixed favorites include both providers but not scenes",()=>assert.deepEqual(favoriteCommands(snap,true).map(c=>c.id),[hue.id,govee.id]));
test("single-provider favorites remain useful",()=>assert.equal(favoriteCommands({targets:[hue,scene]},false).length,1));
test("offline favorites skipped",()=>assert.equal(favoriteCommands({targets:[{...govee,reachable:false}]},true).length,0));
test("missing brightness is not zero",()=>assert.equal(observed({targets:[{...hue,brightness:null}]},{command:"brightness",id:hue.id,value:0}),false));
test("observed command uses stable target id",()=>assert.equal(observed(snap,{command:"power",id:govee.id,value:false}),true));
test("fixed preset key shows configured 65 percent not live 40",()=>assert.equal(viewFor("brightness",settingsFor({brightness:65,targetId:hue.id}, "brightness"),hue,{state:"connected",snapshot:snap}).value,"65%"));
test("explicit offline and missing views",()=>{assert.equal(viewFor("power",{targetId:"gone"},null,{state:"connected",snapshot:snap}).value,"MISSING");assert.equal(viewFor("power",{targetId:hue.id},hue,{state:"offline"}).value,"OFFLINE");});
test("escape hostile device labels in SVG",()=>assert.doesNotMatch(renderKey("power",{top:"<script>&bad",value:"ON"},144),/<script>/));
test("36/72/144 key size and state text",()=>{for(const n of [36,72,144]){const svg=renderKey("power",{top:"POWER",value:"OFFLINE",tone:"error"},n);assert.match(svg,new RegExp('width="'+n+'"'));assert.match(svg,/>OFFLINE</);}});
test("Neo counts power-capable lights and excludes scenes",()=>assert.equal(neoFeedback(snap,"connected").center,"2/3 ON"));
