import test from "node:test";import assert from "node:assert/strict";import {readFileSync,existsSync} from "node:fs";import {resolve,dirname} from "node:path";import {fileURLToPath} from "node:url";
const here=dirname(fileURLToPath(import.meta.url)),root=resolve(here,".."),repo=resolve(root,"..","..");
const json=p=>JSON.parse(readFileSync(p,"utf8"));
const manifest=json(resolve(root,"com.packrat.audio-manager-lite.sdPlugin","manifest.json")),submission=json(resolve(root,"submission.json")),product=json(resolve(repo,"products","audio-manager-lite.json")),map=json(resolve(repo,"products","lite-pro-map.json"));
const html=readFileSync(resolve(root,"ui","config.html"),"utf8"),css=readFileSync(resolve(root,"ui","pi.css"),"utf8"),js=readFileSync(resolve(root,"ui","pi.js"),"utf8"),plugin=readFileSync(resolve(root,"src","plugin.js"),"utf8");
test("Lite exposes exactly two direct device actions",()=>{assert.equal(manifest.Actions.length,2);assert.deepEqual(manifest.Actions.map(x=>x.UUID),["com.packrat.audio-manager-lite.set-output","com.packrat.audio-manager-lite.set-input"]);assert.deepEqual(manifest.Actions.map(x=>x.Name),["Set Output Device","Set Input Device"]);assert.doesNotMatch(JSON.stringify(manifest.Actions),/profile|mute|cycle|status/i);assert.match(plugin,/ACTIONS/);assert.match(plugin,/setDefaultInput/);});
test("Lite ships major-device starter profiles",()=>{assert.deepEqual(manifest.Profiles.map(x=>x.DeviceType),[0,2,7,9]);for(const p of manifest.Profiles)assert.equal(existsSync(resolve(root,"com.packrat.audio-manager-lite.sdPlugin",p.Name+".streamDeckProfile")),true);});
test("Lite to Pro family is registered",()=>{const pair=map.pairs.find(x=>x.lite_id==="audio-manager-lite");assert.ok(pair);assert.equal(pair.pro_id,"audio-manager-pro");assert.equal(pair.platform,"streamdeck");});
test("Lite uses canonical PackRat design and both Pro conversion surfaces",()=>{assert.match(html,/PackRat ↗/);assert.match(html,/Upgrade to Pro ↗/);assert.match(html,/Open Audio Manager Pro ↗/);assert.match(css,/--bg:#080A0E/i);assert.match(css,/--accent:#FFB21E/i);assert.match(css,/overflow-x:hidden/);assert.match(css,/grid-template-columns:minmax\(0,1fr\)/);assert.match(js,/marketplace\.elgato\.com\/maker\/packrat/);});
test("Lite copy makes the edition boundary explicit",()=>{assert.equal(product.price_usd,0);assert.match(submission.description,/output/i);assert.match(submission.description,/input/i);assert.match(submission.description,/Audio Profiles/i);assert.match(submission.description,/Audio Manager Pro/i);});
test("Lite PI keeps configured target separate from current Windows device",()=>{assert.match(html,/Switch to/);assert.match(html,/Windows is using/);assert.match(plugin,/currentDevice/);assert.match(js,/Set Input Device/);assert.match(js,/Set Output Device/);});

test("Lite device selection survives stale live refresh",()=>{assert.match(js,/pendingDevice/);assert.match(js,/applyIncoming/);assert.match(js,/deviceSig/);});
test("Lite bundled profile includes both output and input keys",()=>{const profileSource=readFileSync(resolve(root,"scripts","build-profiles.mjs"),"utf8");assert.match(profileSource,/set-output/);assert.match(profileSource,/set-input/);assert.match(profileSource,/AUDIO DEVICES/);});
