"""Flatten a widget's src/ tree into the single-file index.html iCUE requires.

iCUE loads user widgets from a file:// URL in a GUID-named AppData folder, and
QtWebEngine silently refuses external `<script src>` from there: the tag appears in
the DOM and never executes, so the widget renders blank with no error. Corsair's own
widgets escape this only because they sit next to `common/` in the install dir.
Everything a third-party widget needs must therefore live inside index.html.

Authoring one giant file stops working as soon as widgets share code, so sources
live in `widgets/_src/<slug>/` and shared code in `widgets/_shared/`, and this
flattens them into the packaged `widgets/<slug>/index.html`.

Sources sit OUTSIDE the widget folder on purpose: `icuewidget package` archives the
whole widget directory with no ignore mechanism (verified 2026-08-05 with CLI 0.4.45),
so a `src/` subfolder ships to every customer as dead weight. It measured 10 KB of a
26 KB package.

Layout:
    widgets/_shared/tokens.css       shared, referenced as ../../_shared/tokens.css
    widgets/_src/<slug>/index.html   authored entry point
    widgets/_src/<slug>/app.js       referenced as app.js
    widgets/<slug>/index.html        GENERATED, do not edit
    widgets/<slug>/manifest.json     authored directly, never generated

Relative asset paths that are NOT inlined (a favicon href, an image src) are written
relative to the widget root, because that is where the built file lands.

Usage:
    python widgets/_build/inline.py <slug>
    python widgets/_build/inline.py <slug> --check   # fail if the build is stale
"""
import argparse
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

WIDGETS = Path(__file__).resolve().parents[1]
BANNER = ("<!-- GENERATED by widgets/_build/inline.py from src/. Do not edit; "
          "your changes will be overwritten. -->\n")

VOID = ("area", "base", "br", "col", "embed", "hr", "img", "input",
        "link", "meta", "param", "source", "track", "wbr")

LINK_RE = re.compile(r"""<link\b[^>]*\brel\s*=\s*["']stylesheet["'][^>]*>""", re.I)
SCRIPT_RE = re.compile(r"""<script\b([^>]*)\bsrc\s*=\s*["']([^"']+)["']([^>]*)>\s*</script>""", re.I)
HREF_RE = re.compile(r"""\bhref\s*=\s*["']([^"']+)["']""", re.I)
# Everything that is not a <script> or <style> body, so void-element fixing and the
# XML check never reach inlined CSS or JS.
BLOCK_RE = re.compile(r"<script\b.*?</script>|<style\b.*?</style>", re.S | re.I)


def die(msg):
    print(f"FAIL: {msg}", file=sys.stderr)
    sys.exit(1)


def read_asset(src_dir: Path, ref: str, kind: str) -> str:
    if ref.startswith(("http://", "https://", "//")):
        die(f"{kind} '{ref}' is remote. QtWebEngine blocks remote resources from "
            "file://; vendor the file into the repo and reference it locally.")
    path = (src_dir / ref).resolve()
    if not path.exists():
        die(f"{kind} '{ref}' does not exist (looked in {path})")
    if WIDGETS not in path.parents:
        die(f"{kind} '{ref}' resolves outside widgets/ ({path})")
    return path.read_text(encoding="utf-8")


def self_close_void(html: str) -> str:
    """iCUE parses <head> with a strict XML parser, so void elements must self-close.

    A bare <meta charset="UTF-8"> is valid HTML and invalid XML: the parser never
    closes the tag, fails at </head>, and iCUE rejects the widget with the very
    misleading error "Missing Title Element" even though <title> is present.
    """
    def fix(m):
        tag = m.group(0)
        return tag if tag.rstrip().endswith("/>") else tag[:-1].rstrip() + " />"
    return re.sub(rf"<(?:{'|'.join(VOID)})\b[^>]*>", fix, html)


def build(slug: str, check_only: bool) -> None:
    wdir = WIDGETS / slug
    src_dir = WIDGETS / "_src" / slug
    if not src_dir.is_dir():
        die(f"no widgets/_src/{slug}/ directory. Widgets authored as a single "
            f"hand-written index.html do not need this build step.")
    entry = src_dir / "index.html"
    if not entry.exists():
        die(f"no widgets/_src/{slug}/index.html")
    if not wdir.is_dir():
        die(f"no widgets/{slug}/ package directory (it holds manifest.json and resources/)")

    html = entry.read_text(encoding="utf-8")

    def inline_link(m):
        href = HREF_RE.search(m.group(0))
        if not href:
            return m.group(0)
        css = read_asset(src_dir, href.group(1), "stylesheet")
        return f"<style>\n{css.rstrip()}\n</style>"

    def inline_script(m):
        before, ref, after = m.group(1), m.group(2), m.group(3)
        # A first-party iCUE path resolves against the install dir, not the widget,
        # so it must be left alone rather than inlined or reported missing.
        if ref.startswith(("common/", "../common/")):
            return m.group(0)
        js = read_asset(src_dir, ref, "script")
        attrs = (before + after).replace(" ", "")
        # type="module" cannot survive inlining: a module script has its own scope,
        # so iCUE's injected property globals and `icueEvents = {...}` stop resolving.
        if "type=" in attrs and "module" in attrs:
            die(f"script '{ref}' is type=module. Inlined modules get their own scope, "
                "so icueEvents and the injected property globals stop resolving. "
                "Use a classic script.")
        return f"<script>\n{js.rstrip()}\n</script>"

    n_css = len(LINK_RE.findall(html))
    n_js = len(SCRIPT_RE.findall(html))
    html = LINK_RE.sub(inline_link, html)
    html = SCRIPT_RE.sub(inline_script, html)

    # Fix void elements only outside <script>/<style>, so JS like `a<b` is untouched.
    parts, last = [], 0
    for m in BLOCK_RE.finditer(html):
        parts.append(self_close_void(html[last:m.start()]))
        parts.append(m.group(0))
        last = m.end()
    parts.append(self_close_void(html[last:]))
    html = "".join(parts)

    head = re.search(r"<head>(.*?)</head>", html, re.S)
    if not head:
        die("no <head> in the built document")
    try:
        ET.fromstring("<head>" + BLOCK_RE.sub("", head.group(1)) + "</head>")
    except ET.ParseError as e:
        die(f"head is not well-formed XML after inlining: {e}. iCUE will reject the "
            "widget with 'Missing Title Element'.")

    out = wdir / "index.html"
    built = BANNER + html
    if check_only:
        current = out.read_text(encoding="utf-8") if out.exists() else ""
        if current != built:
            die(f"{slug}/index.html is stale; run: python widgets/_build/inline.py {slug}")
        print(f"OK   {slug}: index.html is up to date")
        return

    out.write_text(built, encoding="utf-8")
    print(f"OK   {slug}: inlined {n_css} stylesheet(s), {n_js} script(s) "
          f"-> {out.relative_to(WIDGETS.parent)} ({len(built):,} bytes)")


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("slug", help="widget folder name under widgets/")
    ap.add_argument("--check", action="store_true",
                    help="fail if the built index.html is out of date instead of writing it")
    args = ap.parse_args()
    build(args.slug, args.check)


if __name__ == "__main__":
    main()
