"""Generate Soccer Tracker's team table across several competitions.

Soccer is the one sport in the slate whose teams do not share a league: following Arsenal and
Real Madrid means following two different ESPN leagues from the same deck. So every row carries
its own leagueId, and the picker groups by competition rather than by conference.

    python plugins/_shared/scripts/gen_soccer_teams.py
    python plugins/_shared/scripts/gen_soccer_teams.py plugins/ultimate-sports/src/teams/soccer.ts
"""
import json
import os
import sys
import urllib.request

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
SITE = "https://site.api.espn.com/apis/site/v2/sports/soccer"
# Optional first argument is a repo-relative output path, for the combined plugin that keeps
# every sport's table side by side instead of one per plugin.
_rel = sys.argv[1] if len(sys.argv) > 1 else "plugins/soccer-tracker/src/teams.ts"
OUT = os.path.join(ROOT, *_rel.split("/"))
# One ".." per segment below plugins/<slug>/, so _shared resolves from any table depth.
_UP = "/".join([".."] * (len(_rel.split("/")) - 2))

# The competitions worth shipping: the five big European leagues, the two continental cups a
# fan actually watches, plus MLS and Liga MX for North America.
COMPETITIONS = [
    ("eng.1", "Premier League"),
    ("esp.1", "LaLiga"),
    ("ger.1", "Bundesliga"),
    ("ita.1", "Serie A"),
    ("fra.1", "Ligue 1"),
    ("uefa.champions", "Champions League"),
    ("uefa.europa", "Europa League"),
    ("usa.1", "MLS"),
    ("mex.1", "Liga MX"),
]


def fetch(url):
    req = urllib.request.Request(url, headers={"accept": "application/json"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read().decode("utf-8"))


def hexed(raw, fallback):
    s = (raw or "").strip().lstrip("#").lower()
    return f"#{s}" if len(s) == 6 else fallback


rows = []
seen = set()
for league_id, label in COMPETITIONS:
    payload = fetch(f"{SITE}/{league_id}/teams?limit=200")
    teams = payload["sports"][0]["leagues"][0]["teams"]
    for wrapper in teams:
        t = wrapper["team"]
        # A club can play in its domestic league and a continental cup; the domestic entry wins,
        # so the picker does not list Arsenal twice.
        if t["id"] in seen:
            continue
        seen.add(t["id"])
        rows.append({
            "id": t["id"],
            "abbr": (t.get("abbreviation") or t.get("shortDisplayName", "")[:3]).upper(),
            "name": t.get("displayName", "").replace('"', ""),
            "color": hexed(t.get("color"), "#1b1f27"),
            "altColor": hexed(t.get("alternateColor"), "#f5faf8"),
            "conference": label,
            "division": label,
            "leagueId": league_id,
        })
    print(f"  {label}: {len(teams)} teams")

order = {label: i for i, (_, label) in enumerate(COMPETITIONS)}
rows.sort(key=lambda r: (order[r["conference"]], r["name"]))

lines = [
    "/**",
    " * Soccer clubs across the shipped competitions, generated by",
    " * plugins/_shared/scripts/gen_soccer_teams.py. Do not hand edit.",
    " *",
    " * Each row carries its own leagueId, because a soccer team's data lives under its",
    " * competition's ESPN path rather than one league-wide one.",
    " *",
    " * Colours are the official club colours, used as the key's colour spine. They are the only",
    " * club branding this product ever renders. No crests, badges or wordmarks, anywhere.",
    " */",
    f'import type {{ SportTeam }} from "{_UP}/_shared/src/sport";',
    "",
    "export const TEAMS: SportTeam[] = [",
]
for r in rows:
    lines.append(
        '\t{ id: "%s", abbr: "%s", name: "%s", color: "%s", altColor: "%s", conference: "%s", '
        'division: "%s", leagueId: "%s" },'
        % (r["id"], r["abbr"], r["name"], r["color"], r["altColor"], r["conference"],
           r["division"], r["leagueId"])
    )
lines += [
    "];",
    "",
    "/** Competitions offered by the league scoreboard key, in the order they should read. */",
    "export const COMPETITIONS: { id: string; name: string }[] = [",
]
for league_id, label in COMPETITIONS:
    lines.append('\t{ id: "%s", name: "%s" },' % (league_id, label))
lines += ["];", ""]

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines))
print(f"wrote {len(rows)} clubs across {len(COMPETITIONS)} competitions to {OUT}")
