/**
 * Canonical Rat Ship Maker Console bridge for iCUE/XENEON widgets.
 * Authentication stays local. The SHIP_KIT is generated by the canonical Rat Ship pipeline.
 */
import { chromium } from 'playwright';
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const args = process.argv.slice(2);
const slug = args.find(x => !x.startsWith('--'));
const kitArg = (args.find(x => x.startsWith('--kit=')) || '').slice(6);
const profileArg = (args.find(x => x.startsWith('--profile=')) || '').slice(10);
const CHECK_KIT = args.includes('--check-kit');
const CHECK_LOGIN = args.includes('--check');
const RESUME = args.includes('--resume');
const SUBMIT = args.includes('--submit');

if (!slug) throw new Error('usage: node tools/ship/maker_console.mjs <slug> --kit=<SHIP_KIT> [--check-kit|--check|--resume|--submit]');

const KIT = kitArg ? resolve(kitArg) : resolve('artifacts', 'ship', slug, 'SHIP_KIT');
if (!existsSync(KIT)) throw new Error(`SHIP_KIT not found: ${KIT}`);

const submissionPath = join(KIT, 'submission.json');
if (!existsSync(submissionPath)) throw new Error('SHIP_KIT/submission.json is required');

const prod = JSON.parse(readFileSync(submissionPath, 'utf8'));
if (prod.slug !== slug || prod.type !== 'widget') throw new Error('submission metadata does not match requested widget');

const galleryFiles = ['03_gallery_01.png','04_gallery_02.png','05_gallery_03.png','06_gallery_04.png'];
const media = ['01_search_icon.png','02_cover.png',...galleryFiles];
const required = ['PASTE_description.txt','PASTE_release_notes.txt',...media];
const missing = required.filter(f => !existsSync(join(KIT, f)));
const packages = readdirSync(KIT).filter(f => /\.icuewidget$/i.test(f));

if (packages.length !== 1) missing.push(`exactly one .icuewidget required, found ${packages.length}`);
for (const key of ['name','version','price_usd','marketplace_category','marketplace_dashboard_sizes','marketplace_language']) {
  if (prod[key] == null || (Array.isArray(prod[key]) && !prod[key].length)) missing.push(`submission.${key}`);
}
if (missing.length) throw new Error(`SHIP_KIT preflight failed:\n${missing.join('\n')}`);

if (CHECK_KIT) {
  console.log(`RAT SHIP KIT PASS: ${prod.name} ${prod.version} | $${prod.price_usd}`);
  console.log(`package: ${packages[0]}`);
  console.log(`gallery order: ${galleryFiles.join(' -> ')}`);
  process.exit(0);
}

const LOG = join(KIT, 'log');
const LOG_ZIP = join(KIT, 'log.zip');
const NO_RETRY = join(LOG, 'NO_RETRY.txt');
mkdirSync(LOG, { recursive: true });

const STATE = join(LOG, 'state.json');
const state = RESUME && existsSync(STATE)
  ? JSON.parse(readFileSync(STATE, 'utf8'))
  : { done: [], uploaded: [], detailsSelections: [], detailsProof: [], pricingProof: null, listboxProof: [], galleryProof: null };

state.done ||= [];
state.uploaded ||= [];
state.detailsSelections ||= [];
state.detailsProof ||= [];
state.pricingProof ||= null;
state.listboxProof ||= [];
state.galleryProof ||= null;

const save = () => writeFileSync(STATE, JSON.stringify(state, null, 2));
const done = id => state.done.includes(id);
const mark = id => { if (!done(id)) state.done.push(id); save(); };

let context = null;
let page = null;
const existingShotNumbers = readdirSync(LOG)
  .map(name => Number((name.match(/^(\d+)-.*\.png$/) || [])[1]))
  .filter(Number.isFinite);
let shot = existingShotNumbers.length ? Math.max(...existingShotNumbers) : 0;

async function snap(target, label) {
  if (!target || target.isClosed()) return;
  await target.screenshot({ path: join(LOG, `${String(++shot).padStart(2, '0')}-${label}.png`) }).catch(() => {});
}

function zipRecoveryLog() {
  if (process.platform !== 'win32' || !existsSync(LOG)) return null;
  const ps = process.env.SystemRoot
    ? join(process.env.SystemRoot, 'System32', 'WindowsPowerShell', 'v1.0', 'powershell.exe')
    : 'powershell.exe';
  const command = `Compress-Archive -Path '${LOG.replace(/'/g, "''")}\\*' -DestinationPath '${LOG_ZIP.replace(/'/g, "''")}' -Force`;
  const result = spawnSync(ps, ['-NoLogo','-NoProfile','-ExecutionPolicy','Bypass','-Command', command], { windowsHide: true, encoding: 'utf8' });
  return result.status === 0 && existsSync(LOG_ZIP) ? LOG_ZIP : null;
}

function stopRetrying(reason) {
  writeFileSync(NO_RETRY, `${reason}\n`, 'utf8');
  throw new Error(reason);
}

async function captureFailure(error) {
  const message = error?.stack || String(error);
  const priorErrors = readdirSync(LOG).filter(name => /^error-\d+\.txt$/i.test(name));
  const errorName = `error-${String(priorErrors.length + 1).padStart(2, '0')}.txt`;
  writeFileSync(join(LOG, errorName), message);
  writeFileSync(join(LOG, 'error.txt'), message);
  await snap(page, 'failure');
  const zipped = zipRecoveryLog();
  if (zipped) console.error(`Rat Ship recovery ZIP: ${zipped}`);
}

async function livePage() {
  if (page && !page.isClosed()) return page;
  const pages = context?.pages().filter(p => !p.isClosed()) || [];
  if (!pages.length) throw new Error('Maker Console closed every page');
  page = pages.at(-1);
  return page;
}

async function visible(locator) {
  return await locator.first().isVisible().catch(() => false);
}

async function signedIn(target) {
  const sign = target.getByRole('button',{name:/^sign in$|^get started$/i})
    .or(target.getByRole('link',{name:/^sign in$|^get started$/i})).first();
  if (await visible(sign)) return false;
  return await target.getByRole('button',{name:/^(account|switch apps)$/i}).first().isVisible().catch(() => false);
}

async function loginFormReady(target) {
  return await target.locator('#kc-form-login').isVisible().catch(() => false);
}

async function waitSignedIn(target, ms = 25000) {
  const end = Date.now() + ms;
  while (Date.now() < end) {
    if (await signedIn(target)) return true;
    await target.waitForTimeout(750);
  }
  return false;
}

async function autoLogin(target) {
  const sign = target.getByRole('button',{name:/^sign in$/i}).or(target.getByRole('link',{name:/^sign in$/i})).first();
  if (!await visible(sign)) return false;

  await sign.click().catch(() => {});
  await target.waitForLoadState('domcontentloaded').catch(() => {});

  const end = Date.now() + 10000;
  while (Date.now() < end) {
    if (await signedIn(target)) return true;
    if (await loginFormReady(target)) break;
    await target.waitForTimeout(250);
  }

  if (await loginFormReady(target)) {
    const autofilled = await target.evaluate(() => {
      const email = document.querySelector('#email');
      const password = document.querySelector('#password');
      return !!email && !!password && email.value.length > 0 && password.value.length > 0;
    }).catch(() => false);

    if (autofilled) {
      console.log('Maker Console login form was autofilled locally. Signing in...');
      await target.locator('#kc-login').click().catch(() => {});
      return await waitSignedIn(target, 30000);
    }
    console.log('Maker Console login form is ready. Complete the one-time local sign in and Rat Ship will continue automatically.');
  }
  return false;
}

async function click(target, re, timeout = 15000) {
  const button = target.getByRole('button',{name:re}).or(target.getByRole('link',{name:re})).first();
  await button.waitFor({state:'visible', timeout});
  const text = ((await button.textContent()) || '').trim();
  if (/^(submit|publish|submit for review)$/i.test(text)) throw new Error(`guard refused ${text}`);
  await button.click({timeout});
  await target.waitForTimeout(900);
}

async function clickIfVisible(target, re) {
  const button = target.getByRole('button',{name:re}).or(target.getByRole('link',{name:re})).first();
  if (!await visible(button)) return false;
  const text = ((await button.textContent()) || '').trim();
  if (/^(submit|publish|submit for review)$/i.test(text)) return false;
  await button.click();
  await target.waitForTimeout(1100);
  return true;
}

async function proseMirror(target, locator, text) {
  await locator.click();
  await target.keyboard.press('ControlOrMeta+A');
  await target.keyboard.press('Delete');
  await target.keyboard.insertText(text);
  await target.waitForTimeout(350);
  const back = ((await locator.innerText().catch(() => '')) || '').trim();
  if (!back) throw new Error('rich text write did not persist');
}

function normalizeReleaseNotes(text) {
  let value = String(text || '').replace(/\r/g,'').trim();
  value = value.replace(/^\s*(initial release|initial version|first release)\s*[:.\-–—]*\s*/i,'').trim();
  if (!value) throw new Error('release notes are empty after normalization');

  const rawLines = value.split('\n').map(line => line.trim()).filter(Boolean);
  let items = [];
  const bulletLines = rawLines.filter(line => /^(?:[-*•]|\d+[.)])\s+/.test(line));
  if (bulletLines.length) {
    items = rawLines.map(line => line.replace(/^(?:[-*•]|\d+[.)])\s+/,'').trim()).filter(Boolean);
  } else {
    items = value.split(/(?<=[.!?])\s+/).map(item => item.trim()).filter(Boolean);
  }

  items = items
    .map(item => item.replace(/^\s*(initial release|initial version|first release)\s*[:.\-–—]*\s*/i,'').trim())
    .filter(Boolean)
    .slice(0,6);

  if (!items.length) throw new Error('release notes have no user-visible bullet content');
  return items.map(item => `• ${item}`).join('\n');
}

async function step(id, label, fn) {
  if (RESUME && done(id)) {
    console.log(`skip ${label}`);
    return;
  }
  console.log(`\n== ${label} ==`);
  await fn();
  mark(id);
  await snap(page, id);
}

async function namedControl(target, name, allowText = false) {
  const escaped = String(name).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const re = new RegExp(`^${escaped}$`, 'i');
  for (const role of ['checkbox','radio','switch','button']) {
    const control = target.getByRole(role,{name:re}).first();
    if (await visible(control)) return control;
  }
  if (allowText) {
    const text = target.getByText(re,{exact:true}).first();
    if (await visible(text)) return text;
  }
  return null;
}

async function selectionSnapshot(control) {
  return await control.evaluate(el => {
    const nested = el.matches('input[type="checkbox"],input[type="radio"]')
      ? el
      : el.querySelector('input[type="checkbox"],input[type="radio"]');
    return {
      tag: el.tagName,
      type: el.getAttribute('type'),
      checked: nested && 'checked' in nested ? Boolean(nested.checked) : null,
      pressed: el.getAttribute('aria-pressed'),
      selected: el.getAttribute('aria-selected'),
      ariaChecked: el.getAttribute('aria-checked'),
      state: el.getAttribute('data-state'),
      selectedData: el.getAttribute('data-selected'),
      cls: String(el.className || ''),
      html: el.outerHTML
    };
  }).catch(() => ({}));
}

function semanticSelection(snapshot) {
  if (snapshot.checked === true) return true;
  if (snapshot.checked === false) return false;

  for (const value of [snapshot.pressed,snapshot.selected,snapshot.ariaChecked,snapshot.selectedData]) {
    if (value === 'true') return true;
    if (value === 'false') return false;
  }

  if (/^(on|checked|selected)$/i.test(snapshot.state || '')) return true;
  if (/^(off|unchecked|unselected)$/i.test(snapshot.state || '')) return false;

  const cls = String(snapshot.cls || '');
  if (/\bbg-surface-inverse\b/.test(cls)) return true;
  if (/\bbg-surface-subtle\b/.test(cls)) return false;

  const tokens = cls.split(/\s+/).filter(Boolean).filter(token => !token.includes(':'));
  if (tokens.some(token => /^(selected|checked|is-selected|is-checked)$/i.test(token))) return true;
  return null;
}

async function ensureNamedSelected(target, name, stateKey, label) {
  if (state.detailsSelections.includes(stateKey)) {
    console.log(`${label}: ${name} (already recorded)`);
    return;
  }

  const control = await namedControl(target, name);
  if (!control) throw new Error(`${label.toLowerCase()} not offered: ${name}`);

  const before = await selectionSnapshot(control);
  const beforeState = semanticSelection(before);

  if (beforeState === true) {
    state.detailsSelections.push(stateKey);
    state.detailsProof.push({key:stateKey,name,label,before,after:before,method:'already-selected'});
    save();
    console.log(`${label}: ${name} (already selected)`);
    return;
  }

  await control.click();
  await target.waitForTimeout(450);

  const after = await selectionSnapshot(control);
  const afterState = semanticSelection(after);
  if (afterState === false) throw new Error(`${label.toLowerCase()} did not stay selected: ${name}`);
  if (afterState === null && JSON.stringify(before) === JSON.stringify(after)) {
    throw new Error(`${label.toLowerCase()} selection produced no detectable state change: ${name}`);
  }

  state.detailsSelections.push(stateKey);
  state.detailsProof.push({key:stateKey,name,label,before,after,method:afterState === true ? 'semantic' : 'visual-state-change'});
  save();
  console.log(`${label}: ${name}`);
}

const OPTION_ALIASES = new Map([['games',['Gaming']]]);
function optionCandidates(value) {
  return [String(value), ...(OPTION_ALIASES.get(String(value).toLowerCase()) || [])];
}

function triggerIncludesValue(label, text, candidate) {
  const wanted = String(candidate).replace(/\s+/g,' ').trim().toLowerCase();
  const normalized = String(text || '').replace(/\s+/g,' ').trim().toLowerCase();
  if (label === 'Category') {
    return normalized.split(',').map(value => value.trim()).filter(Boolean).includes(wanted);
  }
  return normalized === wanted;
}

function recordedListboxIndex(label) {
  for (let i = state.listboxProof.length - 1; i >= 0; i--) {
    const proof = state.listboxProof[i];
    if (proof?.label === label && Number.isInteger(proof.index) && proof.index >= 0) return proof.index;
  }
  return -1;
}

async function inspectListboxes(target) {
  await target.keyboard.press('Escape').catch(() => {});
  const triggers = target.locator('button[aria-haspopup="listbox"]');
  const out = [];
  for (let i = 0; i < await triggers.count(); i++) {
    const trigger = triggers.nth(i);
    const text = ((await trigger.textContent()) || '').replace(/\s+/g,' ').trim();
    let options = [];
    try {
      await trigger.click();
      await target.waitForTimeout(250);
      options = (await target.getByRole('option').allTextContents()).map(x => x.replace(/\s+/g,' ').trim()).filter(Boolean);
      await target.keyboard.press('Escape');
    } catch {}
    out.push({index:i,trigger:text,options});
  }
  writeFileSync(join(LOG,'details-listboxes.json'), JSON.stringify(out,null,2));
  return out;
}

async function selectListboxValue(target, label, requested) {
  await target.keyboard.press('Escape').catch(() => {});
  const candidates = optionCandidates(requested);
  const triggers = target.locator('button[aria-haspopup="listbox"]');

  for (let i=0;i<await triggers.count();i++) {
    const text = ((await triggers.nth(i).textContent()) || '').replace(/\s+/g,' ').trim();
    const matched = candidates.find(candidate => triggerIncludesValue(label,text,candidate));
    if (matched) {
      state.listboxProof.push({label,requested,actual:matched,index:i,method:'already-selected'});
      save();
      console.log(`${label}: ${requested} (already selected)`);
      return;
    }
  }

  const placeholder = label === 'Category' ? /^type$/i : label === 'Language' ? /^language$/i : null;
  let targetTrigger = placeholder ? target.getByRole('button',{name:placeholder}).first() : null;
  let targetIndex = -1;

  if (targetTrigger && await visible(targetTrigger)) {
    const targetHandle = await targetTrigger.elementHandle();
    for (let i=0;i<await triggers.count();i++) {
      const same = targetHandle && await triggers.nth(i).evaluate((el,needle)=>el===needle,targetHandle).catch(()=>false);
      if (same) { targetIndex=i; break; }
    }
  } else {
    targetTrigger = null;
  }

  if (!targetTrigger) {
    const rememberedIndex = recordedListboxIndex(label);
    if (rememberedIndex >= 0 && rememberedIndex < await triggers.count()) {
      targetTrigger = triggers.nth(rememberedIndex);
      targetIndex = rememberedIndex;
    }
  }

  let actual = null;
  if (!targetTrigger) {
    const boxes = await inspectListboxes(target);
    for (const candidate of candidates) {
      const box = boxes.find(item => item.options.some(option => option.toLowerCase() === candidate.toLowerCase()));
      if (box) {
        targetTrigger = target.locator('button[aria-haspopup="listbox"]').nth(box.index);
        targetIndex = box.index;
        actual = candidate;
        break;
      }
    }
  }

  if (!targetTrigger) throw new Error(`Maker Console no longer offers ${label.toLowerCase()}: ${requested}`);

  await targetTrigger.scrollIntoViewIfNeeded().catch(() => {});
  await targetTrigger.click();
  await target.waitForTimeout(250);

  if (!actual) {
    const options = (await target.getByRole('option').allTextContents()).map(x => x.replace(/\s+/g,' ').trim());
    actual = candidates.find(candidate => options.some(option => option.toLowerCase() === candidate.toLowerCase())) || null;
  }
  if (!actual) {
    await target.keyboard.press('Escape').catch(()=>{});
    throw new Error(`Maker Console no longer offers ${label.toLowerCase()}: ${requested}`);
  }

  const escaped = actual.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  await target.getByRole('option',{name:new RegExp(`^${escaped}$`,'i')}).first().click();
  await target.waitForTimeout(250);
  await target.keyboard.press('Escape').catch(() => {});
  await target.waitForTimeout(250);

  let after = ((await targetTrigger.textContent()) || '').replace(/\s+/g,' ').trim();
  if (!triggerIncludesValue(label,after,actual)) {
    await target.waitForTimeout(500);
    after = ((await targetTrigger.textContent()) || '').replace(/\s+/g,' ').trim();
  }
  if (!triggerIncludesValue(label,after,actual)) {
    throw new Error(`${label.toLowerCase()} did not stay selected: ${requested}; control now shows "${after}"`);
  }

  state.listboxProof.push({label,requested,actual,index:targetIndex,method:label === 'Category' ? 'verified-multi-select' : 'verified'});
  save();
  console.log(`${label}: ${requested}${requested === actual ? '' : ` -> ${actual}`}`);
}

async function configurePrice(target) {
  await target.keyboard.press('Escape').catch(() => {});
  const monetization = target.getByText(/^monetization$/i).first();
  if (await monetization.count()) await monetization.scrollIntoViewIfNeeded().catch(() => {});
  await target.waitForTimeout(250);

  if (prod.price_usd > 0) {
    const paid = await namedControl(target, 'Paid');
    if (!paid) throw new Error('paid pricing control not found');

    await paid.scrollIntoViewIfNeeded().catch(() => {});
    const before = await selectionSnapshot(paid);
    if (semanticSelection(before) !== true) await paid.click();
    await target.waitForTimeout(350);

    const after = await selectionSnapshot(paid);
    if (semanticSelection(after) !== true) throw new Error('paid pricing did not stay selected');

    const price = target.getByLabel(/price/i)
      .or(target.locator('input[type="number"],input[inputmode="decimal"]'))
      .or(target.locator('input:not([type=checkbox]):not([type=file]):not([readonly]):visible')).first();

    await price.waitFor({state:'visible',timeout:10000});
    await price.fill(String(prod.price_usd));
    const value = Number(await price.inputValue());
    if (value !== Number(prod.price_usd)) throw new Error(`price mismatch ${value}`);

    state.pricingProof = {mode:'paid',value,expected:Number(prod.price_usd),controlBefore:before,controlAfter:after};
    save();
    console.log(`Price: $${Number(prod.price_usd).toFixed(2)}`);
    return;
  }

  const free = await namedControl(target, 'Free');
  if (!free) throw new Error('free pricing control not found');

  await free.scrollIntoViewIfNeeded().catch(() => {});
  const before = await selectionSnapshot(free);
  if (semanticSelection(before) !== true) await free.click();
  await target.waitForTimeout(350);

  const after = await selectionSnapshot(free);
  if (semanticSelection(after) !== true) throw new Error('free pricing did not stay selected');

  state.pricingProof = {mode:'free',value:0,expected:0,controlBefore:before,controlAfter:after};
  save();
  console.log('Price: Free');
}

async function configureDetails(target) {
  for (const size of prod.marketplace_dashboard_sizes) {
    await ensureNamedSelected(target, size, `size:${String(size).toLowerCase()}`, 'Dashboard size');
  }

  if (prod.marketplace_recommended_orientation) {
    await ensureNamedSelected(
      target,
      prod.marketplace_recommended_orientation,
      `orientation:${String(prod.marketplace_recommended_orientation).toLowerCase()}`,
      'Recommended orientation'
    );
  }

  for (const category of prod.marketplace_category) await selectListboxValue(target, 'Category', category);
  for (const language of prod.marketplace_language) await selectListboxValue(target, 'Language', language);
  await configurePrice(target);

  writeFileSync(join(LOG,'details-selection-proof.json'), JSON.stringify({
    selections:state.detailsSelections,
    proof:state.detailsProof,
    listboxes:state.listboxProof,
    pricing:state.pricingProof
  }, null, 2));

  await snap(target, 'details-before-continue');
  await click(target, /^continue$/i);
}

async function describeFileInputs(target) {
  return await target.locator('input[type="file"]').evaluateAll(inputs => inputs.map((el,index) => ({
    index,
    id:el.id || '',
    name:el.getAttribute('name') || '',
    accept:el.getAttribute('accept') || '',
    multiple:el.hasAttribute('multiple'),
    outerHTML:el.outerHTML,
    context:(el.closest('label,section,div')?.innerText || '').replace(/\s+/g,' ').trim().slice(0,500)
  }))).catch(() => []);
}

function inputScore(info, kind) {
  const haystack = `${info.id} ${info.name} ${info.context}`.toLowerCase();
  let score = 0;
  if (/image|png|jpe?g|webp/.test(info.accept.toLowerCase())) score += 2;

  if (kind === 'icon') {
    if (/media-app-icon|app icon|search icon|\bicon\b/.test(haystack)) score += 20;
    if (/cover|thumbnail|gallery|additional media|screenshots/.test(haystack)) score -= 20;
  } else if (kind === 'cover') {
    if (/cover|thumbnail|hero/.test(haystack)) score += 20;
    if (/app icon|search icon|media-app-icon|gallery|additional media|screenshots/.test(haystack)) score -= 20;
    if (info.multiple) score -= 4;
  } else if (kind === 'gallery') {
    if (/gallery|additional media|screenshots/.test(haystack)) score += 20;
    if (info.multiple) score += 8;
    if (/mp4|video/.test(info.accept.toLowerCase())) score += 4;
    if (/app icon|search icon|media-app-icon|cover|thumbnail|hero/.test(haystack)) score -= 20;
  }
  return score;
}

async function chooseFileInput(target, kind, excluded = new Set()) {
  const inputs = target.locator('input[type="file"]');
  const info = await describeFileInputs(target);
  const ranked = info
    .filter(item => !excluded.has(item.index))
    .map(item => ({...item,score:inputScore(item,kind)}))
    .sort((a,b) => b.score - a.score);

  if (!ranked.length) return null;
  const best = ranked[0];
  const minimum = kind === 'gallery' ? 10 : 10;
  if (best.score < minimum) return null;
  return {locator:inputs.nth(best.index),index:best.index,info:best};
}

async function mediaDiagnostic(target, reason) {
  await snap(target, 'media-diagnostic');
  writeFileSync(join(LOG,'media-file-inputs.json'), JSON.stringify(await describeFileInputs(target),null,2));
  writeFileSync(join(LOG,'media-buttons.json'), JSON.stringify(await target.getByRole('button').allTextContents().catch(() => []),null,2));
  writeFileSync(join(LOG,'media-body.txt'), ((await target.locator('body').innerText().catch(() => '')) || '').slice(0,30000));
  throw new Error(reason);
}

async function setIconAndCover(target) {
  await target.waitForTimeout(700);

  const used = new Set();
  const iconById = target.locator('input#media-app-icon').first();
  if (await iconById.count()) {
    await iconById.setInputFiles(join(KIT,'01_search_icon.png'),{timeout:60000});
    const inputs = target.locator('input[type="file"]');
    const iconHandle = await iconById.elementHandle();
    for (let i=0;i<await inputs.count();i++) {
      if (iconHandle && await inputs.nth(i).evaluate((el,needle)=>el===needle, iconHandle).catch(()=>false)) used.add(i);
    }
    console.log('Search/app icon: dedicated Maker Console field');
  } else {
    const icon = await chooseFileInput(target,'icon');
    if (icon) {
      await icon.locator.setInputFiles(join(KIT,'01_search_icon.png'),{timeout:60000});
      used.add(icon.index);
      console.log('Search/app icon: dedicated labeled field');
    } else {
      console.log('Search/app icon: no dedicated Maker Console field; skipping standalone icon upload');
    }
  }

  await target.waitForTimeout(800);

  let cover = await chooseFileInput(target,'cover',used);
  if (!cover) {
    const zones = target.locator('label,button,[role="button"]').filter({hasText:/cover|thumbnail/i});
    for (let i=0;i<await zones.count();i++) {
      const zone = zones.nth(i);
      const nested = zone.locator('input[type="file"]').first();
      if (await nested.count()) {
        cover = {locator:nested,index:-1,info:{method:'nested-cover-zone'}};
        break;
      }
    }

    if (!cover) {
      for (let i=0;i<await zones.count();i++) {
        const zone = zones.nth(i);
        if (!await zone.isVisible().catch(()=>false)) continue;
        try {
          const chooserPromise = target.waitForEvent('filechooser',{timeout:4000});
          await zone.click();
          const chooser = await chooserPromise;
          await chooser.setFiles(join(KIT,'02_cover.png'));
          cover = {locator:null,index:-1,info:{method:'filechooser-cover-zone'}};
          break;
        } catch {}
      }
    }
  }

  if (!cover) await mediaDiagnostic(target,'cover upload input not found on Maker Console media step');

  if (cover.locator) await cover.locator.setInputFiles(join(KIT,'02_cover.png'),{timeout:60000});
  await target.waitForTimeout(1800);

  const body = await target.locator('body').innerText();
  if (/Thumbnail required|Cover image required/i.test(body)) {
    await mediaDiagnostic(target,'cover upload did not stick');
  }
}

async function countGallery(target) {
  return await target.locator('img[src^="data:image"], img[src*="mp-cdn.elgato.com"]:not([src*="/organizations/"]), video').count().catch(() => null);
}

async function galleryInput(target) {
  const chosen = await chooseFileInput(target,'gallery');
  if (chosen) return chosen;
  const old = target.locator('input[type="file"][accept*="mp4"]').first();
  if (await old.count()) {
    return { locator:old, index:-1, info:{multiple:(await old.getAttribute('multiple')) !== null, method:'legacy'} };
  }
  return null;
}

async function selectedFileNames(input) {
  return await input.evaluate(el => Array.from(el.files || []).map(file => file.name)).catch(() => []);
}
async function uploadGallery(target) {
  const pending = galleryFiles.filter(file => !state.uploaded.includes(file));
  if (!pending.length) {
    mark('6-gallery');
    return;
  }

  const input = await galleryInput(target);
  if (!input) await mediaDiagnostic(target,'gallery upload input not found');

  const before = await countGallery(target);
  if (before == null) throw new Error('cannot verify gallery count');

  const isMultiple = Boolean(input.info?.multiple);
  if (isMultiple && state.uploaded.length === 0) {
    await input.locator.setInputFiles(pending.map(file => join(KIT,file)),{timeout:60000});
    const selected = await selectedFileNames(input.locator);
    if (JSON.stringify(selected) !== JSON.stringify(pending)) {
      await mediaDiagnostic(target,`gallery FileList order mismatch: ${JSON.stringify(selected)} expected ${JSON.stringify(pending)}`);
    }
    await target.waitForTimeout(4500);
    const after = await countGallery(target);
    if (after !== before + pending.length) {
      await mediaDiagnostic(target,`gallery batch invariant failed: ${before} -> ${after}, expected +${pending.length}`);
    }
    state.uploaded.push(...pending);
    state.galleryProof = {mode:'ordered-batch',files:[...pending],selectedFileList:selected,before,after};
    save();
    await snap(target,'gallery-ordered-batch');
    mark('6-gallery');
    return;
  }

  const uploadOrder = isMultiple ? pending : [...pending].reverse();
  for (const file of uploadOrder) {
    const currentInput = await galleryInput(target);
    if (!currentInput) await mediaDiagnostic(target,'gallery upload input disappeared during upload');
    const countBefore = await countGallery(target);
    await currentInput.locator.setInputFiles(join(KIT,file),{timeout:60000});
    const selected = await selectedFileNames(currentInput.locator);
    if (selected.length && selected.at(-1) !== file) throw new Error(`gallery input selected unexpected file for ${file}: ${selected.join(', ')}`);
    await target.waitForTimeout(2500);
    const countAfter = await countGallery(target);
    if (countAfter !== countBefore + 1) throw new Error(`gallery invariant failed for ${file}: ${countBefore} -> ${countAfter}`);
    if (!state.uploaded.includes(file)) state.uploaded.push(file);
    save();
    await snap(target,`gallery-${file}`);
  }

  state.galleryProof = {mode:isMultiple?'individual-append':'reverse-for-prepend',files:[...galleryFiles],uploadOrder};
  save();
  mark('6-gallery');
}

async function editorLooksLikeDetails(target) {
  const size = target.getByRole('button',{name:/^(extra large|large|medium|small)$/i}).first();
  const price = target.getByRole('button',{name:/^(paid|free)$/i}).first();
  return await visible(size) || await visible(price);
}

async function editorLooksLikeMedia(target) {
  if (await target.locator('input[type="file"]').count()) return true;
  const body = ((await target.locator('body').innerText().catch(() => '')) || '').toLowerCase();
  return body.includes('thumbnail') || body.includes('gallery') || body.includes('cover image');
}

async function lockedMonetization(target) {
  const body = ((await target.locator('body').innerText().catch(() => '')) || '').replace(/\s+/g,' ');
  if (!/Monetization/i.test(body) || !/can't switch between paid and free after submitting the product/i.test(body)) return null;
  const section = body.match(/Monetization(.{0,500})/i)?.[1] || body;
  if (/\bPaid\b/i.test(section) && !/\bFree\b/i.test(section)) return 'paid';
  if (/\bFree\b/i.test(section)) return 'free';
  return 'locked';
}

async function rejectUnsafeLockedDraft(target) {
  const locked = await lockedMonetization(target);
  if (!locked) return;

  const expected = Number(prod.price_usd) > 0 ? 'paid' : 'free';
  await snap(target,'locked-monetization');
  const reason = locked === expected
    ? `Existing ${prod.name} product is already past the creation wizard with monetization locked to ${locked}. Rat Ship will not guess how to resume this incomplete draft. Delete the incomplete Maker Console draft/listing and run Rat Ship again.`
    : `Existing ${prod.name} product has monetization locked to ${locked}, but submission.json requires ${expected}${expected === 'paid' ? ` at $${Number(prod.price_usd).toFixed(2)}` : ''}. Delete the incorrect Maker Console draft/listing and run Rat Ship again.`;
  stopRetrying(reason);
}

async function finalReviewReady(target) {
  const submit = target.getByRole('button',{name:/^submit$/i}).first();
  const auto = target.getByRole('checkbox',{name:/automatically publish/i}).or(target.getByRole('switch',{name:/automatically publish/i})).first();
  return await visible(submit) && await visible(auto);
}

async function ensureFinalReview(target) {
  if (await finalReviewReady(target)) return;
  for (let i=0;i<8;i++) {
    if (!await clickIfVisible(target,/^(next|continue)$/i)) break;
    target = await livePage();
    if (await finalReviewReady(target)) return;
  }
  await snap(target,'final-review-missing');
  writeFileSync(join(LOG,'final-review-buttons.json'), JSON.stringify(await target.getByRole('button').allTextContents().catch(() => []),null,2));
  throw new Error('Rat Ship could not reach the Maker Console Submit for review page while resuming.');
}

async function enterExistingEditor(target) {
  for (const re of [/continue editing/i,/edit draft/i,/resume draft/i,/continue setup/i,/edit product/i,/^edit$/i]) {
    if (await clickIfVisible(target,re)) return true;
  }
  return false;
}

async function openExisting(target) {
  await target.goto('https://maker.elgato.com/products',{waitUntil:'domcontentloaded',timeout:45000});
  await target.waitForTimeout(3000);
  const row = target.getByRole('link',{name:new RegExp(`^${prod.name}`,'i')}).or(target.getByText(prod.name,{exact:true})).first();
  if (!await row.isVisible().catch(() => false)) return false;
  await row.click();
  await target.waitForTimeout(3500);
  return true;
}

async function setAutoPublishPreference(target) {
  const desired = prod.marketplace_auto_publish !== false;
  const checkbox = target.getByRole('checkbox',{name:/automatically publish/i})
    .or(target.getByRole('switch',{name:/automatically publish/i})).first();
  await checkbox.waitFor({state:'visible',timeout:10000});

  const isOn = async() => await checkbox.isChecked().catch(async() => await checkbox.getAttribute('aria-checked') === 'true');
  if ((await isOn()) !== desired) await checkbox.click();
  const actual = await isOn();
  if (actual !== desired) {
    throw new Error('auto publish preference did not persist as ' + (desired ? 'enabled' : 'disabled'));
  }

  state.autoPublishProof = {desired,actual};
  save();
  return desired;
}

async function visibleExactProductMatches(target) {
  const matches = target.getByText(prod.name,{exact:true});
  const visibleMatches = [];
  for (let i=0;i<await matches.count();i++) {
    const node = matches.nth(i);
    if (await node.isVisible().catch(() => false)) visibleMatches.push(node);
  }
  return visibleMatches;
}

async function openPublishedProductForUpdate(target) {
  await target.goto('https://maker.elgato.com/products',{waitUntil:'domcontentloaded',timeout:45000});
  await target.waitForTimeout(2500);

  const matches = await visibleExactProductMatches(target);
  if (!matches.length) {
    stopRetrying('Existing published product ' + prod.name + ' was not found in Maker Console. Rat Ship will not create a duplicate update SKU.');
  }

  let chosen = null;
  let identityMethod = 'unique-name';
  const expectedId = String(prod.marketplace_product_id || '').trim().toLowerCase();

  if (expectedId) {
    const idMatches = [];
    for (const node of matches) {
      const proof = await node.evaluate((el,id) => {
        let cur = el;
        for (let depth=0;cur && depth<8;depth++,cur=cur.parentElement) {
          const links = [];
          if (cur.matches && cur.matches('a[href]')) links.push(cur.getAttribute('href') || '');
          if (cur.querySelectorAll) {
            for (const a of cur.querySelectorAll('a[href]')) links.push(a.getAttribute('href') || '');
          }
          const text = String(cur.innerText || '');
          if (links.some(href => String(href).toLowerCase().includes(id)) || text.toLowerCase().includes(id)) {
            return {matched:true,depth,links,text:text.slice(0,1200)};
          }
        }
        return {matched:false};
      }, expectedId).catch(() => ({matched:false}));
      if (proof.matched) idMatches.push({node,proof});
    }

    if (idMatches.length === 1) {
      chosen = idMatches[0].node;
      identityMethod = 'marketplace-id';
      writeFileSync(join(LOG,'existing-product-id-proof.json'),JSON.stringify(idMatches[0].proof,null,2));
    } else if (idMatches.length > 1) {
      stopRetrying('More than one Maker Console row exposes Marketplace product ID ' + expectedId + '. Rat Ship will not guess which listing to update.');
    }
  }

  if (!chosen) {
    if (matches.length !== 1) {
      stopRetrying('More than one visible Maker Console product matches ' + prod.name + ' and the configured Marketplace product ID was not exposed uniquely. Rat Ship will not guess which listing to update.');
    }
    chosen = matches[0];
  }

  state.existingProductProof = {
    name:prod.name,
    marketplaceProductId:expectedId || null,
    matchCount:matches.length,
    identityMethod
  };
  save();

  await chosen.click();
  await target.waitForTimeout(2500);
  target = await livePage();

  const pageText = ((await target.locator('body').innerText().catch(() => '')) || '').replace(/\s+/g,' ');
  if (!pageText.toLowerCase().includes(String(prod.name).toLowerCase())) {
    stopRetrying('Maker Console opened a product page that does not identify itself as ' + prod.name + '.');
  }

  await snap(target,'existing-product-update-target');
  return target;
}

async function openVersionsTab(target) {
  const versions = target.getByRole('tab',{name:/^versions$/i})
    .or(target.getByRole('link',{name:/^versions$/i}))
    .or(target.getByRole('button',{name:/^versions$/i}))
    .or(target.getByText(/^versions$/i,{exact:true})).first();
  await versions.waitFor({state:'visible',timeout:15000});
  await versions.click();
  await target.waitForTimeout(1800);
  target = await livePage();

  const expectedExisting = String(prod.marketplace_existing_version || '').trim();
  if (expectedExisting) {
    const body = (await target.locator('body').innerText().catch(() => '')) || '';
    if (!body.includes(expectedExisting)) {
      await snap(target,'existing-version-not-found');
      stopRetrying('Versions tab does not show expected existing version ' + expectedExisting + ' for ' + prod.name + '. Refusing to create a version on an unverified listing.');
    }
  }
  return target;
}

async function versionPackageInput(target) {
  const inputs = target.locator('input[type="file"]');
  const count = await inputs.count();
  const candidates = [];

  for (let i=0;i<count;i++) {
    const input = inputs.nth(i);
    const accept = String(await input.getAttribute('accept').catch(() => '') || '').toLowerCase();
    const contextText = String(await input.evaluate(el => {
      const parent = el.closest('form,section,div') || el.parentElement;
      return parent ? parent.innerText || '' : '';
    }).catch(() => '') || '').toLowerCase();
    const haystack = accept + ' ' + contextText;
    const packageHint = prod.type === 'plugin'
      ? /streamdeckplugin|stream deck plugin|plugin file/
      : /icuewidget|widget file/;
    if (packageHint.test(haystack)) candidates.push(input);
  }

  if (candidates.length === 1) return candidates[0];
  if (!candidates.length && count === 1) return inputs.first();

  const proof = [];
  for (let i=0;i<count;i++) {
    const input = inputs.nth(i);
    proof.push({
      index:i,
      accept:await input.getAttribute('accept').catch(() => null),
      id:await input.getAttribute('id').catch(() => null),
      name:await input.getAttribute('name').catch(() => null)
    });
  }
  writeFileSync(join(LOG,'version-file-inputs.json'),JSON.stringify(proof,null,2));
  throw new Error('Create version dialog did not expose exactly one recognizable product-file input.');
}

async function runExistingProductVersionUpdate(target) {
  if (!prod.marketplace_product_id) {
    throw new Error('Existing-product update requires submission.marketplace_product_id.');
  }
  if (!prod.marketplace_existing_version) {
    throw new Error('Existing-product update requires submission.marketplace_existing_version.');
  }

  target = await openPublishedProductForUpdate(target);
  target = await openVersionsTab(target);

  const createVersion = target.getByRole('button',{name:/^create version$/i})
    .or(target.getByRole('link',{name:/^create version$/i})).first();
  await createVersion.waitFor({state:'visible',timeout:15000});
  await createVersion.click();
  await target.waitForTimeout(1200);
  target = await livePage();

  await step('update-file','Upload new product version',async() => {
    const input = await versionPackageInput(target);
    await input.setInputFiles(join(KIT,packages[0]),{timeout:60000});
    await target.waitForTimeout(1800);

    const body = (await target.locator('body').innerText().catch(() => '')) || '';
    if (!body.includes(prod.version)) {
      if (await clickIfVisible(target,/^(next|continue)$/i)) {
        target = await livePage();
        await target.waitForTimeout(1200);
      }
    }
  });

  await step('update-notes','Set release notes',async() => {
    target = await livePage();
    const body = (await target.locator('body').innerText().catch(() => '')) || '';
    if (!body.includes(prod.version)) {
      await snap(target,'update-version-missing');
      throw new Error('Create version flow does not show candidate version ' + prod.version + ' after package upload.');
    }

    const notes = target.getByLabel(/release notes|what.s new/i)
      .or(target.getByRole('textbox',{name:/release|notes/i}))
      .or(target.locator('[contenteditable="true"]')).first();
    await notes.waitFor({state:'visible',timeout:10000});

    const normalizedNotes = normalizeReleaseNotes(readFileSync(join(KIT,'PASTE_release_notes.txt'),'utf8'));
    writeFileSync(join(LOG,'release-notes-normalized.txt'),normalizedNotes + '\n','utf8');
    await proseMirror(target,notes,normalizedNotes);
  });

  await step('update-autopublish','Set version auto publish preference',async() => {
    target = await livePage();
    await setAutoPublishPreference(target);
  });

  target = await livePage();
  const finalAction = target.getByRole('button',{name:/^(submit|submit for review|create version)$/i}).last();
  await finalAction.waitFor({state:'visible',timeout:15000});
  await snap(target,'existing-version-final');

  state.versionUpdateProof = {
    marketplaceProductId:String(prod.marketplace_product_id),
    priorVersion:String(prod.marketplace_existing_version),
    candidateVersion:String(prod.version),
    autoPublish:prod.marketplace_auto_publish !== false,
    finalAction:((await finalAction.textContent()) || '').trim()
  };
  save();

  if (!SUBMIT) {
    console.log('STAGED VERSION UPDATE: ' + prod.name + ' ' + prod.version + '. Nothing submitted.');
    return 0;
  }

  await finalAction.click();
  await target.waitForTimeout(6000);
  target = await livePage();
  await snap(target,'existing-version-after-submit');

  const after = (await target.locator('body').innerText().catch(() => '')) || '';
  if (!after.includes(prod.version)) {
    throw new Error('Maker Console did not show submitted candidate version ' + prod.version + ' after version submission.');
  }
  console.log('SUBMITTED VERSION UPDATE: ' + prod.name + ' ' + prod.version + ' | ' + target.url());
  return 0;
}

async function run() {
  const profileDir = profileArg ? resolve(profileArg) : join(ROOT,'.playwright-profile');
  context = await chromium.launchPersistentContext(profileDir,{headless:false,viewport:{width:1500,height:950}});
  context.pages().forEach(p => p.on('crash',() => console.error(`RAT SHIP PAGE CRASH: ${p.url()}`)));
  context.on('page',p => p.on('crash',() => console.error(`RAT SHIP PAGE CRASH: ${p.url()}`)));

  page = context.pages()[0] ?? await context.newPage();
  await page.goto('https://maker.elgato.com',{waitUntil:'domcontentloaded',timeout:45000});
  await page.waitForTimeout(1200);

  let auth = await signedIn(page);
  if (!auth) auth = await autoLogin(page);
  await snap(page, auth ? 'signed-in' : 'signed-out');

  if (CHECK_LOGIN) {
    console.log(auth ? 'MAKER LOGIN PASS' : 'MAKER LOGIN REQUIRED');
    return auth ? 0 : 2;
  }

  if (!auth) {
    console.log('Maker Console authentication is local. Sign in in the opened browser; this run will continue automatically when the session is ready.');
    auth = await waitSignedIn(page, 15 * 60_000);
    if (!auth) throw new Error('Maker Console login was not completed within 15 minutes');
  }

  if (prod.marketplace_existing_product_update === true) {
    return await runExistingProductVersionUpdate(page);
  }

  const editing = await openExisting(page);

  if (editing) {
    console.log(`Existing Maker Console product found for ${prod.name}. Continuing that draft/listing.`);
    page = await livePage();
    await enterExistingEditor(page);
    page = await livePage();
    await rejectUnsafeLockedDraft(page);

    if (await editorLooksLikeDetails(page)) {
      await step('4-details','Set category, dashboard sizes, orientation, language and price',async() => configureDetails(page));
    } else if (await editorLooksLikeMedia(page)) {
      mark('4-details');
    } else if (await finalReviewReady(page)) {
      for (const id of ['4-details','5-media','6-gallery','6-continue','7-notes','8-autopublish']) mark(id);
    } else {
      await snap(page,'resume-unknown');
      writeFileSync(join(LOG,'resume-buttons.json'),JSON.stringify(await page.getByRole('button').allTextContents().catch(() => []),null,2));
      throw new Error('Existing Maker Console draft was found, but Rat Ship could not identify its current edit step.');
    }
  } else {
    await step('1-create','Create Widget draft',async() => {
      await click(page,/create product|new product|add product/i);
      const choice = page.getByRole('radio',{name:/^widget$/i}).or(page.getByText(/^widget$/i)).or(page.getByRole('button',{name:/^widget$/i})).first();
      await choice.click();
      await click(page,/^(next|continue)$/i);
    });

    await step('2-file','Upload .icuewidget',async() => {
      page = await livePage();
      const input = page.locator('input[type="file"]').first();
      await input.setInputFiles(join(KIT,packages[0]));
      await click(page,/^(next|continue)$/i,180000);
    });

    await step('3-copy','Verify name and set description',async() => {
      page = await livePage();
      const readonlyName = page.locator('input[readonly][maxlength]').first();
      await readonlyName.waitFor({state:'visible',timeout:10000});
      const name = (await readonlyName.inputValue()).trim();
      if (name !== prod.name) throw new Error(`manifest name mismatch: ${name}`);

      const desc = page.locator('#description').or(page.locator('div[role="textbox"]')).or(page.locator('[contenteditable="true"]')).first();
      await proseMirror(page,desc,readFileSync(join(KIT,'PASTE_description.txt'),'utf8').trim());
      await click(page,/^create product$/i);
      page = await livePage();
    });

    await step('4-details','Set category, dashboard sizes, orientation, language and price',async() => configureDetails(page));
  }

  await step('5-media','Upload icon and cover',async() => setIconAndCover(page));
  page = await livePage();
  await uploadGallery(page);

  await step('6-continue','Continue past media',async() => {
    for (let i=0;i<6;i++) {
      await click(page,/^(next|continue)$/i,30000).catch(() => {});
      await page.waitForTimeout(1800);
      if (!await page.getByRole('button',{name:/^replace$/i}).first().isVisible().catch(() => false)) return;
    }
    throw new Error('media slide would not advance');
  });

  await step('7-notes','Verify version and set release notes',async() => {
    page = await livePage();
    const body = await page.locator('body').innerText();
    if (!body.includes(prod.version)) throw new Error(`summary does not show version ${prod.version}`);

    const notes = page.getByLabel(/release notes|what.s new/i)
      .or(page.getByRole('textbox',{name:/release|notes/i}))
      .or(page.locator('[contenteditable="true"]')).first();

    const normalizedNotes = normalizeReleaseNotes(readFileSync(join(KIT,'PASTE_release_notes.txt'),'utf8'));
    writeFileSync(join(LOG,'release-notes-normalized.txt'), `${normalizedNotes}\n`, 'utf8');
    await proseMirror(page,notes,normalizedNotes);
  });

  await step('8-autopublish','Set auto publish preference',async() => {
    await setAutoPublishPreference(page);
  });

  page = await livePage();
  await ensureFinalReview(page);
  await snap(page,'final');

  if (!SUBMIT) {
    console.log(`STAGED: ${prod.name}. Nothing submitted. Re-run with --resume --submit after review.`);
    return 0;
  }

  if (state.uploaded.length !== galleryFiles.length) throw new Error('gallery is incomplete, refusing submit');
  if (!state.galleryProof || JSON.stringify(state.galleryProof.files) !== JSON.stringify(galleryFiles)) {
    throw new Error('gallery order is not proven, refusing submit');
  }

  const summary = await page.locator('body').innerText();
  if (!summary.includes(prod.name) || !summary.includes(prod.version)) throw new Error('summary name/version mismatch, refusing submit');

  if (prod.price_usd > 0) {
    const expected = Number(prod.price_usd);
    if (!state.pricingProof || state.pricingProof.mode !== 'paid' || Number(state.pricingProof.value) !== expected) {
      throw new Error(`details step does not prove paid pricing at $${expected.toFixed(2)}, refusing submit`);
    }
  } else if (!state.pricingProof || state.pricingProof.mode !== 'free') {
    throw new Error('details step does not prove free pricing, refusing submit');
  }

  for (const size of prod.marketplace_dashboard_sizes) {
    const key = `size:${String(size).toLowerCase()}`;
    if (!state.detailsSelections.includes(key)) throw new Error(`details step does not prove dashboard size ${size}, refusing submit`);
  }

  if (prod.marketplace_recommended_orientation) {
    const key = `orientation:${String(prod.marketplace_recommended_orientation).toLowerCase()}`;
    if (!state.detailsSelections.includes(key)) throw new Error(`details step does not prove recommended orientation ${prod.marketplace_recommended_orientation}`);
  }

  const expectedAutoPublish = prod.marketplace_auto_publish !== false;
  const checkbox = page.getByRole('checkbox',{name:/automatically publish/i}).or(page.getByRole('switch',{name:/automatically publish/i})).first();
  const autoPublish = await checkbox.isChecked().catch(async() => await checkbox.getAttribute('aria-checked') === 'true');
  if (autoPublish !== expectedAutoPublish) throw new Error('auto publish preference mismatch, refusing submit');

  const submit = page.getByRole('button',{name:/^submit$/i}).first();
  await submit.waitFor({state:'visible',timeout:15000});
  await submit.click();
  await page.waitForTimeout(8000);
  await snap(page,'after-submit');
  console.log(`SUBMITTED: ${prod.name} | ${page.url()}`);
  return 0;
}

try {
  const code = await run();
  if (context) await context.close().catch(() => {});
  process.exit(code);
} catch (error) {
  await captureFailure(error);
  if (context) await context.close().catch(() => {});
  throw error;
}