import {cp,mkdir,rm,writeFile} from "node:fs/promises";import {resolve} from "node:path";
const root=resolve(import.meta.dirname,".."),plugin=resolve(root,"com.packrat.audio-manager-lite.sdPlugin"),bin=resolve(plugin,"bin"),imgs=resolve(plugin,"imgs"),ui=resolve(plugin,"ui"),nativeOut=resolve(plugin,"native","win-x64");
for(const name of ["PackRat.AudioCore.pdb","PackRat.AudioManagerLite.Helper.pdb"])await rm(resolve(nativeOut,name),{force:true});
await rm(bin,{recursive:true,force:true});await rm(imgs,{recursive:true,force:true});await rm(ui,{recursive:true,force:true});await mkdir(bin,{recursive:true});await mkdir(ui,{recursive:true});
for(const f of ["config.html","pi.css","pi.js"])await cp(resolve(root,"ui",f),resolve(ui,f));
const pd=resolve(imgs,"plugin"),cd=resolve(imgs,"category"),outDir=resolve(imgs,"actions","set-output"),inDir=resolve(imgs,"actions","set-input");await mkdir(pd,{recursive:true});await mkdir(cd,{recursive:true});await mkdir(outDir,{recursive:true});await mkdir(inDir,{recursive:true});
await cp(resolve(root,"..","..","tools","art","assets","ratpack-icon-transparent.png"),resolve(pd,"packrat-logo.png"));
await cp(resolve(root,"..","..","tools","art","assets","ratpack-icon-transparent.png"),resolve(pd,"icon.png"));await cp(resolve(root,"..","..","tools","art","assets","ratpack-icon-transparent.png"),resolve(pd,"icon@2x.png"));
const speaker=(accent="#FFB21E",fg="#F5F7FA")=>`<path d="M35 43h21l22-17v57L56 66H35z" fill="none" stroke="${fg}" stroke-width="6" stroke-linejoin="round"/><path d="M89 40c8 8 8 21 0 29M99 31c14 14 14 31 0 45" fill="none" stroke="${accent}" stroke-width="5" stroke-linecap="round"/>`;
const mic=(accent="#FFB21E",fg="#F5F7FA")=>`<rect x="60" y="20" width="24" height="45" rx="12" fill="none" stroke="${fg}" stroke-width="6"/><path d="M49 55c0 16 9 25 23 25s23-9 23-25M72 80v14M58 95h28" fill="none" stroke="${accent}" stroke-width="6" stroke-linecap="round"/>`;
await writeFile(resolve(cd,"icon.svg"),`<svg xmlns="http://www.w3.org/2000/svg" width="56" height="56" viewBox="0 0 144 144">${speaker("#fff","#fff")}</svg>`);
await writeFile(resolve(outDir,"icon.svg"),`<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 144 144">${speaker("#fff","#fff")}</svg>`);
await writeFile(resolve(outDir,"key.svg"),`<svg xmlns="http://www.w3.org/2000/svg" width="144" height="144" viewBox="0 0 144 144"><rect width="144" height="144" rx="24" fill="#090C12"/>${speaker()}</svg>`);
await writeFile(resolve(inDir,"icon.svg"),`<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 144 144">${mic("#fff","#fff")}</svg>`);
await writeFile(resolve(inDir,"key.svg"),`<svg xmlns="http://www.w3.org/2000/svg" width="144" height="144" viewBox="0 0 144 144"><rect width="144" height="144" rx="24" fill="#090C12"/>${mic()}</svg>`);
console.log("Built Audio Manager Lite UI and assets");
