"""Flatten a widget source tree into the single-file index.html iCUE requires.

Canonical RatPack XENEON build tool.

Sources live in widgets/_src/<slug>/ and shipping files live in widgets/<slug>/.
Local stylesheets and classic scripts referenced by the source HTML are inlined into
widgets/<slug>/index.html before official iCUE validation and packaging.

The generated document installs two small compatibility layers for iCUE property
controls. The first exposes a static direct-binding reader for controls that iCUE
creates as document-level JavaScript bindings. The second runs after authored widget
scripts and mirrors those live values into writable globalThis properties for older
RatPack runtimes that still read window properties. When a mirrored binding changes,
the watcher invokes the widget's normal onDataUpdated lifecycle immediately.

Usage:
    python tools/xeneon/inline.py <slug>
    python tools/xeneon/inline.py <slug> --check
"""
import argparse
import json
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
WIDGETS = REPO / "widgets"
BANNER = ("<!-- GENERATED by tools/xeneon/inline.py from widgets/_src/. "
          "Do not edit; your changes will be overwritten. -->\n")

VOID = ("area", "base", "br", "col", "embed", "hr", "img", "input",
        "link", "meta", "param", "source", "track", "wbr")
LINK_RE = re.compile(r"""<link\b[^>]*\brel\s*=\s*["']stylesheet["'][^>]*>""", re.I)
SCRIPT_RE = re.compile(r"""<script\b([^>]*)\bsrc\s*=\s*["']([^"']+)["']([^>]*)>\s*</script>""", re.I)
HREF_RE = re.compile(r"""\bhref\s*=\s*["']([^"']+)["']""", re.I)
BLOCK_RE = re.compile(r"<script\b.*?</script>|<style\b.*?</style>", re.S | re.I)
JSON_SCRIPT_RE = re.compile(r"""<script\b(?=[^>]*\btype\s*=\s*["']application/json["'])[^>]*>(.*?)</script>""", re.S | re.I)
SCRIPT_ID_RE = re.compile(r"""\bid\s*=\s*["']([^"']+)["']""", re.I)
META_RE = re.compile(r"<meta\b[^>]*>", re.I)
NAME_RE = re.compile(r"""\bname\s*=\s*["']([^"']+)["']""", re.I)
CONTENT_RE = re.compile(r"""\bcontent\s*=\s*["']([^"']+)["']""", re.I)
JS_IDENTIFIER_RE = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")


def die(msg):
    print(f"FAIL: {msg}", file=sys.stderr)
    sys.exit(1)


def read_asset(src_dir: Path, ref: str, kind: str) -> str:
    if ref.startswith(("http://", "https://", "//")):
        die(f"{kind} '{ref}' is remote; vendor it into the repository first")
    path = (src_dir / ref).resolve()
    if not path.exists():
        die(f"{kind} '{ref}' does not exist (looked in {path})")
    if WIDGETS not in path.parents:
        die(f"{kind} '{ref}' resolves outside widgets/ ({path})")
    return path.read_text(encoding="utf-8")


def self_close_void(html: str) -> str:
    def fix(match):
        tag = match.group(0)
        return tag if tag.rstrip().endswith("/>") else tag[:-1].rstrip() + " />"
    return re.sub(rf"<(?:{'|'.join(VOID)})\b[^>]*>", fix, html)


def icue_property_names(html: str) -> list[str]:
    names = []
    for match in META_RE.finditer(html):
        tag = match.group(0)
        name_match = NAME_RE.search(tag)
        if not name_match or name_match.group(1).lower() != "x-icue-property":
            continue
        content_match = CONTENT_RE.search(tag)
        if not content_match:
            continue
        name = content_match.group(1).strip()
        if JS_IDENTIFIER_RE.match(name) and name not in names:
            names.append(name)
    return names


def binding_bridge(html: str) -> str:
    names = icue_property_names(html)
    if not names:
        return ""
    encoded = json.dumps(names, ensure_ascii=True, separators=(",", ":"))
    cases = []
    for name in names:
        key = json.dumps(name, ensure_ascii=True)
        cases.append(
            f"    case {key}:\n"
            f"      try {{ return typeof {name} !== 'undefined' ? {name} : undefined; }}\n"
            f"      catch (error) {{ return undefined; }}"
        )
    case_block = "\n".join(cases)
    return f"""<script>
(function () {{
  var names = {encoded};
  function readBinding(name) {{
    switch (name) {{
{case_block}
      default: return undefined;
    }}
  }}
  globalThis.__ratpackIcueRead = readBinding;
  names.forEach(function (name) {{
    try {{
      if (Object.prototype.hasOwnProperty.call(globalThis, name)) return;
      if (readBinding(name) === undefined) return;
      Object.defineProperty(globalThis, name, {{
        configurable: true,
        enumerable: true,
        get: function () {{ return readBinding(name); }}
      }});
    }} catch (error) {{}}
  }});
  globalThis.__ratpackIcueBindingBridge = {{ version: 2, mode: 'direct-binding', names: names.slice() }};
}})();
</script>"""


def binding_runtime_sync(html: str) -> str:
    names = icue_property_names(html)
    if not names:
        return ""
    encoded = json.dumps(names, ensure_ascii=True, separators=(",", ":"))
    return f"""<script>
(function () {{
  var names = {encoded};
  var snapshot = Object.create(null);
  var started = false;
  var notifying = false;

  function stable(value) {{
    if (value === undefined) return '__ratpack_undefined__';
    try {{ return JSON.stringify(value); }}
    catch (error) {{ return String(value); }}
  }}

  function mirror(name, value) {{
    if (value === undefined) return;
    try {{
      var descriptor = Object.getOwnPropertyDescriptor(globalThis, name);
      if (descriptor && (descriptor.get || descriptor.set)) return;
      if (!descriptor) {{
        Object.defineProperty(globalThis, name, {{
          configurable: true,
          enumerable: true,
          writable: true,
          value: value
        }});
      }} else if (descriptor.writable !== false) {{
        globalThis[name] = value;
      }}
    }} catch (error) {{}}
  }}

  function sync() {{
    var reader = globalThis.__ratpackIcueRead;
    if (typeof reader !== 'function') return;
    var changed = false;
    names.forEach(function (name) {{
      var value;
      try {{ value = reader(name); }}
      catch (error) {{ return; }}
      if (value === undefined) return;
      var next = stable(value);
      if (Object.prototype.hasOwnProperty.call(snapshot, name) && snapshot[name] !== next) changed = true;
      snapshot[name] = next;
      mirror(name, value);
    }});

    if (started && changed && !notifying) {{
      try {{
        var events = globalThis.icueEvents;
        if (events && typeof events.onDataUpdated === 'function') {{
          notifying = true;
          events.onDataUpdated();
        }}
      }} catch (error) {{}}
      finally {{ notifying = false; }}
    }}
    started = true;
  }}

  sync();
  globalThis.__ratpackIcueSyncGlobals = sync;
  globalThis.__ratpackIcueBindingSync = {{ version: 1, names: names.slice() }};
  setInterval(sync, 200);
}})();
</script>"""


def validate_metadata_json_scripts(html: str) -> None:
    """Validate iCUE JSON metadata as both JSON and strict-XML-safe text.

    Real iCUE parses metadata in <head> more strictly than a browser. A raw '&' or
    '<' inside x-icue-groups can therefore be valid JSON yet still make the importer
    report an unsupported/corrupted widget with a meta-parameter JSON error.
    """
    for match in JSON_SCRIPT_RE.finditer(html):
        block = match.group(0)
        body = match.group(1)
        start_tag = block.split(">", 1)[0]
        id_match = SCRIPT_ID_RE.search(start_tag)
        script_id = id_match.group(1) if id_match else "application/json metadata"

        try:
            json.loads(body)
        except json.JSONDecodeError as exc:
            die(
                f"{script_id} contains invalid JSON at line {exc.lineno}, "
                f"column {exc.colno}: {exc.msg}"
            )

        try:
            ET.fromstring("<script>" + body + "</script>")
        except ET.ParseError as exc:
            die(
                f"{script_id} metadata is not XML-safe: {exc}. "
                "Escape raw XML characters inside metadata JSON; for example, "
                "use \\u0026 when an ampersand must survive JSON parsing."
            )


def validate_control_attributes(html: str) -> None:
    for match in META_RE.finditer(html):
        tag = match.group(0)
        name_match = NAME_RE.search(tag)
        if not name_match or name_match.group(1).lower() != "x-icue-property":
            continue
        type_match = re.search(r"\bdata-type\s*=\s*[\"']([^\"']+)[\"']", tag, re.I)
        control_type = type_match.group(1).strip().lower() if type_match else ""
        if control_type in {"combobox", "tab-buttons"} and re.search(r"\bdata-options\s*=", tag, re.I):
            die("iCUE control uses unsupported data-options; use data-values for combobox/tab-buttons")


def build(slug: str, check_only: bool) -> None:
    wdir = WIDGETS / slug
    src_dir = WIDGETS / "_src" / slug
    if not src_dir.is_dir():
        die(f"no widgets/_src/{slug}/ directory")
    entry = src_dir / "index.html"
    if not entry.exists():
        die(f"no widgets/_src/{slug}/index.html")
    if not wdir.is_dir():
        die(f"no widgets/{slug}/ package directory")

    html = entry.read_text(encoding="utf-8")
    validate_metadata_json_scripts(html)
    validate_control_attributes(html)

    def inline_link(match):
        href = HREF_RE.search(match.group(0))
        if not href:
            return match.group(0)
        css = read_asset(src_dir, href.group(1), "stylesheet")
        return f"<style>\n{css.rstrip()}\n</style>"

    def inline_script(match):
        before, ref, after = match.group(1), match.group(2), match.group(3)
        if ref.startswith(("common/", "../common/")):
            return match.group(0)
        js = read_asset(src_dir, ref, "script")
        attrs = (before + after).replace(" ", "")
        if "type=" in attrs and "module" in attrs:
            die(f"script '{ref}' is type=module; use a classic script for iCUE inlining")
        return f"<script>\n{js.rstrip()}\n</script>"

    html = LINK_RE.sub(inline_link, html)
    html = SCRIPT_RE.sub(inline_script, html)

    bridge = binding_bridge(html)
    if bridge:
        if "</head>" not in html:
            die("no </head> in built document")
        html = html.replace("</head>", bridge + "\n</head>", 1)

    runtime_sync = binding_runtime_sync(html)
    if runtime_sync:
        if "</body>" not in html:
            die("no </body> in built document")
        html = html.replace("</body>", runtime_sync + "\n</body>", 1)

    parts, last = [], 0
    for match in BLOCK_RE.finditer(html):
        parts.append(self_close_void(html[last:match.start()]))
        parts.append(match.group(0))
        last = match.end()
    parts.append(self_close_void(html[last:]))
    html = "".join(parts)

    head = re.search(r"<head>(.*?)</head>", html, re.S)
    if not head:
        die("no <head> in built document")
    try:
        ET.fromstring("<head>" + BLOCK_RE.sub("", head.group(1)) + "</head>")
    except ET.ParseError as exc:
        die(f"head is not well formed XML after inlining: {exc}")

    out = wdir / "index.html"
    built = BANNER + html
    if check_only:
        current = out.read_text(encoding="utf-8") if out.exists() else ""
        if current != built:
            die(f"{slug}/index.html is stale; run: python tools/xeneon/inline.py {slug}")
        print(f"OK   {slug}: index.html is up to date")
        return

    out.write_text(built, encoding="utf-8")
    print(f"OK   {slug}: generated {out.relative_to(REPO)} ({len(built):,} chars)")


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("slug")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    build(args.slug, args.check)


if __name__ == "__main__":
    main()
