let websocket=null,uuid=null,actionUuid="",settings={},monitorRows=[],profiles=[],profileError=null;
const A={brightness:"com.packrat.monitormanagerpro.brightness",contrast:"com.packrat.monitormanagerpro.contrast",volume:"com.packrat.monitormanagerpro.volume",power:"com.packrat.monitormanagerpro.power",input:"com.packrat.monitormanagerpro.input",refresh:"com.packrat.monitormanagerpro.refresh-rate",resolution:"com.packrat.monitormanagerpro.resolution",hdr:"com.packrat.monitormanagerpro.hdr",topology:"com.packrat.monitormanagerpro.topology",orientation:"com.packrat.monitormanagerpro.orientation",save:"com.packrat.monitormanagerpro.save-profile",apply:"com.packrat.monitormanagerpro.apply-profile"};
function connectElgatoStreamDeckSocket(inPort,inUUID,inRegisterEvent,inInfo,inActionInfo){
  uuid=inUUID;try{const info=JSON.parse(inActionInfo);actionUuid=info.action??"";settings=info.payload?.settings??{};}catch{settings={};}
  websocket=new WebSocket("ws://127.0.0.1:"+inPort);
  websocket.onopen=()=>{websocket.send(JSON.stringify({event:inRegisterEvent,uuid:inUUID}));build();render();requestData();};
  websocket.onmessage=(event)=>{
    const message=JSON.parse(event.data);
    if(message.event==="didReceiveSettings"){settings=message.payload?.settings??{};render();}
    if(message.event==="sendToPropertyInspector"&&message.payload?.type==="monitor-data"){
      monitorRows=Array.isArray(message.payload.monitors)?message.payload.monitors:[];profiles=Array.isArray(message.payload.profiles)?message.payload.profiles:[];profileError=message.payload.profileError??null;
      finishRefresh(profileError?"Monitor scan updated; profile store needs attention.":"Monitor data updated.");render();
    }
    if(message.event==="sendToPropertyInspector"&&message.payload?.type==="monitor-error")finishRefresh("Refresh failed: "+String(message.payload.message??"unknown error"));
  };
}
function save(){if(websocket?.readyState===WebSocket.OPEN)websocket.send(JSON.stringify({event:"setSettings",action:actionUuid,context:uuid,payload:settings}));}
function finishRefresh(text){const b=document.getElementById("refresh");if(b){b.disabled=false;b.textContent="Refresh";}const s=document.getElementById("refreshStatus");if(s)s.textContent=text??"";}
function requestData(){const b=document.getElementById("refresh");if(b){b.disabled=true;b.textContent="Refreshing…";}const s=document.getElementById("refreshStatus");if(s)s.textContent="Scanning Windows and monitor capabilities…";if(websocket?.readyState===WebSocket.OPEN)websocket.send(JSON.stringify({event:"sendToPlugin",action:actionUuid,context:uuid,payload:{type:"refresh-monitors"}}));}
function opt(select,value,label){const o=document.createElement("option");o.value=value;o.textContent=label;select.appendChild(o);}
function currentMonitor(){return settings.monitorKey?monitorRows.find(m=>m.monitorKey===settings.monitorKey)??null:monitorRows[0]??null;}
function state(v){return typeof v==="string"?v:(v?.state??"UNKNOWN");}
function inputLabel(v){const labels={15:"DisplayPort 1",16:"DisplayPort 2",17:"HDMI 1",18:"HDMI 2",27:"USB-C"};return labels[v]??("Input 0x"+Number(v).toString(16).toUpperCase().padStart(2,"0"));}
function modeEntries(row){
  const source=Array.isArray(row?.modes)?row.modes:[];const orientation=Number(row?.currentMode?.orientation??0);
  let entries=source.map((m,i)=>({m,i})).filter(({m})=>Number(m.orientation??0)===orientation);if(!entries.length)entries=source.map((m,i)=>({m,i}));
  const maxArea=entries.reduce((max,{m})=>Math.max(max,Number(m.width)*Number(m.height)),0);
  const group=(m)=>{const area=Number(m.width)*Number(m.height);if(area===maxArea)return 0;if(Number(m.width)===1920&&Number(m.height)===1080)return 1;return 2;};
  return entries.sort((a,b)=>group(a.m)-group(b.m)||(group(a.m)===2?(Number(b.m.width)*Number(b.m.height)-Number(a.m.width)*Number(a.m.height)):0)||Number(b.m.frequency)-Number(a.m.frequency)||Number(b.m.width)-Number(a.m.width));
}
function render(){
  const continuous=[A.brightness,A.contrast,A.volume].includes(actionUuid);
  document.getElementById("continuousCard")?.classList.toggle("hidden",!continuous);document.getElementById("powerCard")?.classList.toggle("hidden",actionUuid!==A.power);document.getElementById("inputCard")?.classList.toggle("hidden",actionUuid!==A.input);document.getElementById("refreshCard")?.classList.toggle("hidden",actionUuid!==A.refresh);document.getElementById("resolutionCard")?.classList.toggle("hidden",actionUuid!==A.resolution);document.getElementById("hdrCard")?.classList.toggle("hidden",actionUuid!==A.hdr);document.getElementById("topologyCard")?.classList.toggle("hidden",actionUuid!==A.topology);document.getElementById("orientationCard")?.classList.toggle("hidden",actionUuid!==A.orientation);document.getElementById("profileCard")?.classList.toggle("hidden",![A.save,A.apply].includes(actionUuid));
  const mon=document.getElementById("monitor");if(mon){mon.textContent="";if(settings.monitorKey&&!monitorRows.some(m=>m.monitorKey===settings.monitorKey))opt(mon,settings.monitorKey,"Configured monitor not connected");for(const m of monitorRows){const suffix=m.currentMode?(" · "+m.currentMode.width+"×"+m.currentMode.height+" @ "+m.currentMode.frequency+" Hz"):"";opt(mon,m.monitorKey,(m.description||m.deviceName)+(m.primary?" · PRIMARY":"")+suffix);}if(!settings.monitorKey&&monitorRows[0]){settings={...settings,monitorKey:monitorRows[0].monitorKey};save();}mon.value=settings.monitorKey??"";}
  const row=currentMonitor();const caps=document.getElementById("capabilities");if(caps){if(!row)caps.textContent=settings.monitorKey?"CONFIGURED MONITOR NOT CONNECTED":"NO MONITOR DETECTED";else{const c=row.capabilities??{};caps.textContent=["BRIGHTNESS "+state(c.brightness),"CONTRAST "+state(c.contrast),"INPUT "+state(c.input),"VOLUME "+state(c.volume),"POWER "+state(c.power),"HDR "+state(c.hdr)].join(" · ");}}
  if(continuous){const field=actionUuid===A.brightness?"value":actionUuid===A.contrast?"contrast":"volume";const label=actionUuid===A.brightness?"Brightness":actionUuid===A.contrast?"Contrast":"Monitor Volume";document.getElementById("continuousTitle").textContent=label;const input=document.getElementById("continuousValue");if(input&&document.activeElement!==input)input.value=String(settings[field]??(field==="value"?65:50));const step=document.getElementById("continuousStep");if(step&&document.activeElement!==step)step.value=String(settings.step??2);}
  const power=document.getElementById("power");if(power)power.value=settings.power??"toggle";const hdr=document.getElementById("hdr");if(hdr)hdr.value=settings.hdr??"toggle";const topology=document.getElementById("topology");if(topology)topology.value=settings.topology??"extend";const orientation=document.getElementById("orientation");if(orientation)orientation.value=String(settings.orientation??0);
  const input=document.getElementById("inputValue");if(input&&!row)input.textContent="";if(input&&row){input.textContent="";const values=row.capabilities?.input?.values??[];if(!values.length)opt(input,"","No advertised input values");for(const v of values)opt(input,String(v),inputLabel(v));input.value=settings.inputValue===undefined?"":String(settings.inputValue);}
  const refresh=document.getElementById("refreshRate");if(refresh&&!row)refresh.textContent="";if(refresh&&row){const cur=row.currentMode;let rates=[...new Set((row.modes??[]).filter(m=>!cur||(m.width===cur.width&&m.height===cur.height&&Number(m.orientation??0)===Number(cur.orientation??0))).map(m=>Number(m.frequency)))];rates=rates.filter(rate=>rate>=60||rate===Number(cur?.frequency)).sort((a,b)=>b-a);refresh.textContent="";for(const rate of rates)opt(refresh,String(rate),String(rate)+" Hz");refresh.value=String(settings.refreshRate??cur?.frequency??rates[0]??60);}
  const mode=document.getElementById("resolutionMode");if(mode&&!row)mode.textContent="";if(mode&&row){mode.textContent="";const entries=modeEntries(row);entries.forEach(({m,i})=>opt(mode,String(i),m.width+"×"+m.height+" @ "+m.frequency+" Hz"));const found=entries.find(({m})=>m.width===settings.width&&m.height===settings.height&&m.frequency===settings.frequency&&Number(m.orientation??0)===Number(settings.orientation??row.currentMode?.orientation??0));mode.value=String(found?.i??entries[0]?.i??0);}
  const list=document.getElementById("profiles");if(list){list.textContent="";opt(list,"","Saved profiles…");for(const name of profiles)opt(list,name,name);}const profile=document.getElementById("profileName");if(profile&&document.activeElement!==profile)profile.value=settings.profileName??"";const profileStatus=document.getElementById("profileStoreStatus");if(profileStatus)profileStatus.textContent=profileError?String(profileError):"Profiles are stored locally in %APPDATA%\\PackRat\\Monitor Manager.";document.getElementById("profileReset")?.classList.toggle("hidden",!profileError);
}
function build(){
  document.getElementById("refresh")?.addEventListener("click",requestData);document.getElementById("monitor")?.addEventListener("change",e=>{settings={...settings,monitorKey:e.target.value};save();render();});
  document.getElementById("continuousValue")?.addEventListener("change",e=>{const field=actionUuid===A.brightness?"value":actionUuid===A.contrast?"contrast":"volume";settings={...settings,[field]:Number(e.target.value)};save();});document.getElementById("continuousStep")?.addEventListener("change",e=>{settings={...settings,step:Number(e.target.value)};save();});document.getElementById("power")?.addEventListener("change",e=>{settings={...settings,power:e.target.value};save();});document.getElementById("inputValue")?.addEventListener("change",e=>{settings={...settings,inputValue:Number(e.target.value)};save();});document.getElementById("refreshRate")?.addEventListener("change",e=>{settings={...settings,refreshRate:Number(e.target.value)};save();});
  document.getElementById("resolutionMode")?.addEventListener("change",e=>{const m=currentMonitor()?.modes?.[Number(e.target.value)];if(!m)return;settings={...settings,modePreset:undefined,width:m.width,height:m.height,frequency:m.frequency,orientation:Number(m.orientation??0)};save();});document.getElementById("hdr")?.addEventListener("change",e=>{settings={...settings,hdr:e.target.value};save();});document.getElementById("topology")?.addEventListener("change",e=>{settings={...settings,topology:e.target.value};save();});document.getElementById("orientation")?.addEventListener("change",e=>{settings={...settings,orientation:Number(e.target.value)};save();});
  document.getElementById("profileName")?.addEventListener("input",e=>{settings={...settings,profileName:e.target.value.trim()};save();});document.getElementById("profileReset")?.addEventListener("click",()=>{if(!confirm("Back up the existing Monitor Manager profile file and start a new empty profile store?"))return;if(websocket?.readyState===WebSocket.OPEN)websocket.send(JSON.stringify({event:"sendToPlugin",action:actionUuid,context:uuid,payload:{type:"reset-profiles"}}));});
}
